/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CampaignCloneQueryAsSubResourceAttributes
 */
export interface CampaignCloneQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof CampaignCloneQueryAsSubResourceAttributes
     */
    newName?: string;
}

/**
 * Check if a given object implements the CampaignCloneQueryAsSubResourceAttributes interface.
 */
export function instanceOfCampaignCloneQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CampaignCloneQueryAsSubResourceAttributesFromJSON(json: any): CampaignCloneQueryAsSubResourceAttributes {
    return CampaignCloneQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function CampaignCloneQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCloneQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'newName': !exists(json, 'new_name') ? undefined : json['new_name'],
    };
}

export function CampaignCloneQueryAsSubResourceAttributesToJSON(value?: CampaignCloneQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'new_name': value.newName,
    };
}

