/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CampaignSendJobPartialUpdateQueryAsSubResourceAttributes } from './CampaignSendJobPartialUpdateQueryAsSubResourceAttributes';
import {
    CampaignSendJobPartialUpdateQueryAsSubResourceAttributesFromJSON,
    CampaignSendJobPartialUpdateQueryAsSubResourceAttributesFromJSONTyped,
    CampaignSendJobPartialUpdateQueryAsSubResourceAttributesToJSON,
} from './CampaignSendJobPartialUpdateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface CampaignSendJobPartialUpdateQueryAsSubResource
 */
export interface CampaignSendJobPartialUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CampaignSendJobPartialUpdateQueryAsSubResource
     */
    type: CampaignSendJobPartialUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CampaignSendJobPartialUpdateQueryAsSubResource
     */
    id: string;
    /**
     * 
     * @type {CampaignSendJobPartialUpdateQueryAsSubResourceAttributes}
     * @memberof CampaignSendJobPartialUpdateQueryAsSubResource
     */
    attributes: CampaignSendJobPartialUpdateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const CampaignSendJobPartialUpdateQueryAsSubResourceTypeEnum = {
    CampaignSendJob: 'campaign-send-job'
} as const;
export type CampaignSendJobPartialUpdateQueryAsSubResourceTypeEnum = typeof CampaignSendJobPartialUpdateQueryAsSubResourceTypeEnum[keyof typeof CampaignSendJobPartialUpdateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CampaignSendJobPartialUpdateQueryAsSubResource interface.
 */
export function instanceOfCampaignSendJobPartialUpdateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CampaignSendJobPartialUpdateQueryAsSubResourceFromJSON(json: any): CampaignSendJobPartialUpdateQueryAsSubResource {
    return CampaignSendJobPartialUpdateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CampaignSendJobPartialUpdateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignSendJobPartialUpdateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': CampaignSendJobPartialUpdateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function CampaignSendJobPartialUpdateQueryAsSubResourceToJSON(value?: CampaignSendJobPartialUpdateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': CampaignSendJobPartialUpdateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

