/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CampaignCloneQueryAsSubResource } from './CampaignCloneQueryAsSubResource';
import {
    CampaignCloneQueryAsSubResourceFromJSON,
    CampaignCloneQueryAsSubResourceFromJSONTyped,
    CampaignCloneQueryAsSubResourceToJSON,
} from './CampaignCloneQueryAsSubResource';

/**
 * 
 * @export
 * @interface CampaignCloneQuery
 */
export interface CampaignCloneQuery {
    /**
     * 
     * @type {CampaignCloneQueryAsSubResource}
     * @memberof CampaignCloneQuery
     */
    data: CampaignCloneQueryAsSubResource;
}

/**
 * Check if a given object implements the CampaignCloneQuery interface.
 */
export function instanceOfCampaignCloneQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CampaignCloneQueryFromJSON(json: any): CampaignCloneQuery {
    return CampaignCloneQueryFromJSONTyped(json, false);
}

export function CampaignCloneQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCloneQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CampaignCloneQueryAsSubResourceFromJSON(json['data']),
    };
}

export function CampaignCloneQueryToJSON(value?: CampaignCloneQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CampaignCloneQueryAsSubResourceToJSON(value.data),
    };
}

