/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CampaignSendJobCreateQueryAsSubResourceAttributes } from './CampaignSendJobCreateQueryAsSubResourceAttributes';
import {
    CampaignSendJobCreateQueryAsSubResourceAttributesFromJSON,
    CampaignSendJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    CampaignSendJobCreateQueryAsSubResourceAttributesToJSON,
} from './CampaignSendJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface CampaignSendJobCreateQueryAsSubResource
 */
export interface CampaignSendJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CampaignSendJobCreateQueryAsSubResource
     */
    type: CampaignSendJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CampaignSendJobCreateQueryAsSubResourceAttributes}
     * @memberof CampaignSendJobCreateQueryAsSubResource
     */
    attributes: CampaignSendJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const CampaignSendJobCreateQueryAsSubResourceTypeEnum = {
    CampaignSendJob: 'campaign-send-job'
} as const;
export type CampaignSendJobCreateQueryAsSubResourceTypeEnum = typeof CampaignSendJobCreateQueryAsSubResourceTypeEnum[keyof typeof CampaignSendJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CampaignSendJobCreateQueryAsSubResource interface.
 */
export function instanceOfCampaignSendJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CampaignSendJobCreateQueryAsSubResourceFromJSON(json: any): CampaignSendJobCreateQueryAsSubResource {
    return CampaignSendJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CampaignSendJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignSendJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': CampaignSendJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function CampaignSendJobCreateQueryAsSubResourceToJSON(value?: CampaignSendJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': CampaignSendJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

