/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AudiencesSubObject } from './AudiencesSubObject';
import {
    AudiencesSubObjectFromJSON,
    AudiencesSubObjectFromJSONTyped,
    AudiencesSubObjectToJSON,
} from './AudiencesSubObject';
import type { SendOptionsSubObject } from './SendOptionsSubObject';
import {
    SendOptionsSubObjectFromJSON,
    SendOptionsSubObjectFromJSONTyped,
    SendOptionsSubObjectToJSON,
} from './SendOptionsSubObject';
import type { SendStrategySubObject } from './SendStrategySubObject';
import {
    SendStrategySubObjectFromJSON,
    SendStrategySubObjectFromJSONTyped,
    SendStrategySubObjectToJSON,
} from './SendStrategySubObject';
import type { TrackingOptionsSubObject } from './TrackingOptionsSubObject';
import {
    TrackingOptionsSubObjectFromJSON,
    TrackingOptionsSubObjectFromJSONTyped,
    TrackingOptionsSubObjectToJSON,
} from './TrackingOptionsSubObject';

/**
 * 
 * @export
 * @interface CampaignPartialUpdateQueryAsSubResourceAttributes
 */
export interface CampaignPartialUpdateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof CampaignPartialUpdateQueryAsSubResourceAttributes
     */
    name?: string;
    /**
     * 
     * @type {AudiencesSubObject}
     * @memberof CampaignPartialUpdateQueryAsSubResourceAttributes
     */
    audiences?: AudiencesSubObject;
    /**
     * 
     * @type {SendOptionsSubObject}
     * @memberof CampaignPartialUpdateQueryAsSubResourceAttributes
     */
    sendOptions?: SendOptionsSubObject;
    /**
     * 
     * @type {TrackingOptionsSubObject}
     * @memberof CampaignPartialUpdateQueryAsSubResourceAttributes
     */
    trackingOptions?: TrackingOptionsSubObject;
    /**
     * 
     * @type {SendStrategySubObject}
     * @memberof CampaignPartialUpdateQueryAsSubResourceAttributes
     */
    sendStrategy?: SendStrategySubObject;
}

/**
 * Check if a given object implements the CampaignPartialUpdateQueryAsSubResourceAttributes interface.
 */
export function instanceOfCampaignPartialUpdateQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CampaignPartialUpdateQueryAsSubResourceAttributesFromJSON(json: any): CampaignPartialUpdateQueryAsSubResourceAttributes {
    return CampaignPartialUpdateQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function CampaignPartialUpdateQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignPartialUpdateQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'audiences': !exists(json, 'audiences') ? undefined : AudiencesSubObjectFromJSON(json['audiences']),
        'sendOptions': !exists(json, 'send_options') ? undefined : SendOptionsSubObjectFromJSON(json['send_options']),
        'trackingOptions': !exists(json, 'tracking_options') ? undefined : TrackingOptionsSubObjectFromJSON(json['tracking_options']),
        'sendStrategy': !exists(json, 'send_strategy') ? undefined : SendStrategySubObjectFromJSON(json['send_strategy']),
    };
}

export function CampaignPartialUpdateQueryAsSubResourceAttributesToJSON(value?: CampaignPartialUpdateQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'audiences': AudiencesSubObjectToJSON(value.audiences),
        'send_options': SendOptionsSubObjectToJSON(value.sendOptions),
        'tracking_options': TrackingOptionsSubObjectToJSON(value.trackingOptions),
        'send_strategy': SendStrategySubObjectToJSON(value.sendStrategy),
    };
}

