/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CampaignSendJobCreateQueryAsSubResource } from './CampaignSendJobCreateQueryAsSubResource';
import {
    CampaignSendJobCreateQueryAsSubResourceFromJSON,
    CampaignSendJobCreateQueryAsSubResourceFromJSONTyped,
    CampaignSendJobCreateQueryAsSubResourceToJSON,
} from './CampaignSendJobCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CampaignSendJobCreateQuery
 */
export interface CampaignSendJobCreateQuery {
    /**
     * 
     * @type {CampaignSendJobCreateQueryAsSubResource}
     * @memberof CampaignSendJobCreateQuery
     */
    data: CampaignSendJobCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the CampaignSendJobCreateQuery interface.
 */
export function instanceOfCampaignSendJobCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CampaignSendJobCreateQueryFromJSON(json: any): CampaignSendJobCreateQuery {
    return CampaignSendJobCreateQueryFromJSONTyped(json, false);
}

export function CampaignSendJobCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignSendJobCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CampaignSendJobCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function CampaignSendJobCreateQueryToJSON(value?: CampaignSendJobCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CampaignSendJobCreateQueryAsSubResourceToJSON(value.data),
    };
}

