/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogVariantCreateQueryAsSubResourceAttributes
 */
export interface CatalogVariantCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    externalId: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    catalogType?: string;
    /**
     * The integration type. Currently, this can only be set to $custom (and defaults to $custom if not included in the payload).
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    integrationType?: CatalogVariantCreateQueryAsSubResourceAttributesIntegrationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    sku: string;
    /**
     * A field that controls product visibility in product feeds/blocks. This field has two options:     DENY (1): a product will not appear in dynamic product recommendation feeds and blocks if it is out of stock.     CONTINUE (2): a product can appear in dynamic product recommendation feeds and blocks regardless of inventory quantity.     UNKNOWN (0): the behavior will be the same as if it were set to 2 [Default]
     * @type {number}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    inventoryPolicy: CatalogVariantCreateQueryAsSubResourceAttributesInventoryPolicyEnum;
    /**
     * 
     * @type {number}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    inventoryQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    imageFullUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    imageThumbnailUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    images?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    customMetadata?: object;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogVariantCreateQueryAsSubResourceAttributes
     */
    published?: boolean;
}


/**
 * @export
 */
export const CatalogVariantCreateQueryAsSubResourceAttributesIntegrationTypeEnum = {
    Custom: '$custom'
} as const;
export type CatalogVariantCreateQueryAsSubResourceAttributesIntegrationTypeEnum = typeof CatalogVariantCreateQueryAsSubResourceAttributesIntegrationTypeEnum[keyof typeof CatalogVariantCreateQueryAsSubResourceAttributesIntegrationTypeEnum];

/**
 * @export
 */
export const CatalogVariantCreateQueryAsSubResourceAttributesInventoryPolicyEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type CatalogVariantCreateQueryAsSubResourceAttributesInventoryPolicyEnum = typeof CatalogVariantCreateQueryAsSubResourceAttributesInventoryPolicyEnum[keyof typeof CatalogVariantCreateQueryAsSubResourceAttributesInventoryPolicyEnum];


/**
 * Check if a given object implements the CatalogVariantCreateQueryAsSubResourceAttributes interface.
 */
export function instanceOfCatalogVariantCreateQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "externalId" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "sku" in value;
    isInstance = isInstance && "inventoryPolicy" in value;
    isInstance = isInstance && "inventoryQuantity" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function CatalogVariantCreateQueryAsSubResourceAttributesFromJSON(json: any): CatalogVariantCreateQueryAsSubResourceAttributes {
    return CatalogVariantCreateQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function CatalogVariantCreateQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogVariantCreateQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalId': json['external_id'],
        'catalogType': !exists(json, 'catalog_type') ? undefined : json['catalog_type'],
        'integrationType': !exists(json, 'integration_type') ? undefined : json['integration_type'],
        'title': json['title'],
        'description': json['description'],
        'sku': json['sku'],
        'inventoryPolicy': json['inventory_policy'],
        'inventoryQuantity': json['inventory_quantity'],
        'price': json['price'],
        'url': json['url'],
        'imageFullUrl': !exists(json, 'image_full_url') ? undefined : json['image_full_url'],
        'imageThumbnailUrl': !exists(json, 'image_thumbnail_url') ? undefined : json['image_thumbnail_url'],
        'images': !exists(json, 'images') ? undefined : json['images'],
        'customMetadata': !exists(json, 'custom_metadata') ? undefined : json['custom_metadata'],
        'published': !exists(json, 'published') ? undefined : json['published'],
    };
}

export function CatalogVariantCreateQueryAsSubResourceAttributesToJSON(value?: CatalogVariantCreateQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external_id': value.externalId,
        'catalog_type': value.catalogType,
        'integration_type': value.integrationType,
        'title': value.title,
        'description': value.description,
        'sku': value.sku,
        'inventory_policy': value.inventoryPolicy,
        'inventory_quantity': value.inventoryQuantity,
        'price': value.price,
        'url': value.url,
        'image_full_url': value.imageFullUrl,
        'image_thumbnail_url': value.imageThumbnailUrl,
        'images': value.images,
        'custom_metadata': value.customMetadata,
        'published': value.published,
    };
}

