/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogItemUpdateJobCreateQueryAsSubResourceAttributes } from './CatalogItemUpdateJobCreateQueryAsSubResourceAttributes';
import {
    CatalogItemUpdateJobCreateQueryAsSubResourceAttributesFromJSON,
    CatalogItemUpdateJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    CatalogItemUpdateJobCreateQueryAsSubResourceAttributesToJSON,
} from './CatalogItemUpdateJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface CatalogItemUpdateJobCreateQueryAsSubResource
 */
export interface CatalogItemUpdateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemUpdateJobCreateQueryAsSubResource
     */
    type: CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogItemUpdateJobCreateQueryAsSubResourceAttributes}
     * @memberof CatalogItemUpdateJobCreateQueryAsSubResource
     */
    attributes: CatalogItemUpdateJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum = {
    CatalogItemBulkUpdateJob: 'catalog-item-bulk-update-job'
} as const;
export type CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum = typeof CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogItemUpdateJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CatalogItemUpdateJobCreateQueryAsSubResource interface.
 */
export function instanceOfCatalogItemUpdateJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CatalogItemUpdateJobCreateQueryAsSubResourceFromJSON(json: any): CatalogItemUpdateJobCreateQueryAsSubResource {
    return CatalogItemUpdateJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CatalogItemUpdateJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItemUpdateJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': CatalogItemUpdateJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function CatalogItemUpdateJobCreateQueryAsSubResourceToJSON(value?: CatalogItemUpdateJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': CatalogItemUpdateJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

