/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogItemCreateQueryAsSubResource } from './CatalogItemCreateQueryAsSubResource';
import {
    CatalogItemCreateQueryAsSubResourceFromJSON,
    CatalogItemCreateQueryAsSubResourceFromJSONTyped,
    CatalogItemCreateQueryAsSubResourceToJSON,
} from './CatalogItemCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CatalogItemCreateJobCreateQueryAsSubResourceAttributes
 */
export interface CatalogItemCreateJobCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {Array<CatalogItemCreateQueryAsSubResource>}
     * @memberof CatalogItemCreateJobCreateQueryAsSubResourceAttributes
     */
    items: Array<CatalogItemCreateQueryAsSubResource>;
}

/**
 * Check if a given object implements the CatalogItemCreateJobCreateQueryAsSubResourceAttributes interface.
 */
export function instanceOfCatalogItemCreateJobCreateQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function CatalogItemCreateJobCreateQueryAsSubResourceAttributesFromJSON(json: any): CatalogItemCreateJobCreateQueryAsSubResourceAttributes {
    return CatalogItemCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function CatalogItemCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItemCreateJobCreateQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CatalogItemCreateQueryAsSubResourceFromJSON)),
    };
}

export function CatalogItemCreateJobCreateQueryAsSubResourceAttributesToJSON(value?: CatalogItemCreateJobCreateQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(CatalogItemCreateQueryAsSubResourceToJSON)),
    };
}

