/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CatalogItemDeleteQueryAsSubResource
 */
export interface CatalogItemDeleteQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDeleteQueryAsSubResource
     */
    type: CatalogItemDeleteQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogItemDeleteQueryAsSubResource
     */
    id: string;
}


/**
 * @export
 */
export const CatalogItemDeleteQueryAsSubResourceTypeEnum = {
    CatalogItem: 'catalog-item'
} as const;
export type CatalogItemDeleteQueryAsSubResourceTypeEnum = typeof CatalogItemDeleteQueryAsSubResourceTypeEnum[keyof typeof CatalogItemDeleteQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CatalogItemDeleteQueryAsSubResource interface.
 */
export function instanceOfCatalogItemDeleteQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CatalogItemDeleteQueryAsSubResourceFromJSON(json: any): CatalogItemDeleteQueryAsSubResource {
    return CatalogItemDeleteQueryAsSubResourceFromJSONTyped(json, false);
}

export function CatalogItemDeleteQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItemDeleteQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function CatalogItemDeleteQueryAsSubResourceToJSON(value?: CatalogItemDeleteQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

