/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogVariantCreateQueryAsSubResource } from './CatalogVariantCreateQueryAsSubResource';
import {
    CatalogVariantCreateQueryAsSubResourceFromJSON,
    CatalogVariantCreateQueryAsSubResourceFromJSONTyped,
    CatalogVariantCreateQueryAsSubResourceToJSON,
} from './CatalogVariantCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CatalogVariantCreateJobCreateQueryAsSubResourceAttributes
 */
export interface CatalogVariantCreateJobCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {Array<CatalogVariantCreateQueryAsSubResource>}
     * @memberof CatalogVariantCreateJobCreateQueryAsSubResourceAttributes
     */
    variants: Array<CatalogVariantCreateQueryAsSubResource>;
}

/**
 * Check if a given object implements the CatalogVariantCreateJobCreateQueryAsSubResourceAttributes interface.
 */
export function instanceOfCatalogVariantCreateJobCreateQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "variants" in value;

    return isInstance;
}

export function CatalogVariantCreateJobCreateQueryAsSubResourceAttributesFromJSON(json: any): CatalogVariantCreateJobCreateQueryAsSubResourceAttributes {
    return CatalogVariantCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function CatalogVariantCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogVariantCreateJobCreateQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'variants': ((json['variants'] as Array<any>).map(CatalogVariantCreateQueryAsSubResourceFromJSON)),
    };
}

export function CatalogVariantCreateJobCreateQueryAsSubResourceAttributesToJSON(value?: CatalogVariantCreateJobCreateQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'variants': ((value.variants as Array<any>).map(CatalogVariantCreateQueryAsSubResourceToJSON)),
    };
}

