/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogItemUpdateJobCreateQueryAsSubResource } from './CatalogItemUpdateJobCreateQueryAsSubResource';
import {
    CatalogItemUpdateJobCreateQueryAsSubResourceFromJSON,
    CatalogItemUpdateJobCreateQueryAsSubResourceFromJSONTyped,
    CatalogItemUpdateJobCreateQueryAsSubResourceToJSON,
} from './CatalogItemUpdateJobCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CatalogItemUpdateJobCreateQuery
 */
export interface CatalogItemUpdateJobCreateQuery {
    /**
     * 
     * @type {CatalogItemUpdateJobCreateQueryAsSubResource}
     * @memberof CatalogItemUpdateJobCreateQuery
     */
    data: CatalogItemUpdateJobCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the CatalogItemUpdateJobCreateQuery interface.
 */
export function instanceOfCatalogItemUpdateJobCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CatalogItemUpdateJobCreateQueryFromJSON(json: any): CatalogItemUpdateJobCreateQuery {
    return CatalogItemUpdateJobCreateQueryFromJSONTyped(json, false);
}

export function CatalogItemUpdateJobCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItemUpdateJobCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CatalogItemUpdateJobCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function CatalogItemUpdateJobCreateQueryToJSON(value?: CatalogItemUpdateJobCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CatalogItemUpdateJobCreateQueryAsSubResourceToJSON(value.data),
    };
}

