/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogCategoryDeleteJobCreateQueryAsSubResource } from './CatalogCategoryDeleteJobCreateQueryAsSubResource';
import {
    CatalogCategoryDeleteJobCreateQueryAsSubResourceFromJSON,
    CatalogCategoryDeleteJobCreateQueryAsSubResourceFromJSONTyped,
    CatalogCategoryDeleteJobCreateQueryAsSubResourceToJSON,
} from './CatalogCategoryDeleteJobCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CatalogCategoryDeleteJobCreateQuery
 */
export interface CatalogCategoryDeleteJobCreateQuery {
    /**
     * 
     * @type {CatalogCategoryDeleteJobCreateQueryAsSubResource}
     * @memberof CatalogCategoryDeleteJobCreateQuery
     */
    data: CatalogCategoryDeleteJobCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the CatalogCategoryDeleteJobCreateQuery interface.
 */
export function instanceOfCatalogCategoryDeleteJobCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CatalogCategoryDeleteJobCreateQueryFromJSON(json: any): CatalogCategoryDeleteJobCreateQuery {
    return CatalogCategoryDeleteJobCreateQueryFromJSONTyped(json, false);
}

export function CatalogCategoryDeleteJobCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogCategoryDeleteJobCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CatalogCategoryDeleteJobCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function CatalogCategoryDeleteJobCreateQueryToJSON(value?: CatalogCategoryDeleteJobCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CatalogCategoryDeleteJobCreateQueryAsSubResourceToJSON(value.data),
    };
}

