/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogCategoryUpdateJobCreateQueryAsSubResource } from './CatalogCategoryUpdateJobCreateQueryAsSubResource';
import {
    CatalogCategoryUpdateJobCreateQueryAsSubResourceFromJSON,
    CatalogCategoryUpdateJobCreateQueryAsSubResourceFromJSONTyped,
    CatalogCategoryUpdateJobCreateQueryAsSubResourceToJSON,
} from './CatalogCategoryUpdateJobCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface CatalogCategoryUpdateJobCreateQuery
 */
export interface CatalogCategoryUpdateJobCreateQuery {
    /**
     * 
     * @type {CatalogCategoryUpdateJobCreateQueryAsSubResource}
     * @memberof CatalogCategoryUpdateJobCreateQuery
     */
    data: CatalogCategoryUpdateJobCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the CatalogCategoryUpdateJobCreateQuery interface.
 */
export function instanceOfCatalogCategoryUpdateJobCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CatalogCategoryUpdateJobCreateQueryFromJSON(json: any): CatalogCategoryUpdateJobCreateQuery {
    return CatalogCategoryUpdateJobCreateQueryFromJSONTyped(json, false);
}

export function CatalogCategoryUpdateJobCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogCategoryUpdateJobCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CatalogCategoryUpdateJobCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function CatalogCategoryUpdateJobCreateQueryToJSON(value?: CatalogCategoryUpdateJobCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CatalogCategoryUpdateJobCreateQueryAsSubResourceToJSON(value.data),
    };
}

