/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogVariantUpdateQueryAsSubResourceAttributes } from './CatalogVariantUpdateQueryAsSubResourceAttributes';
import {
    CatalogVariantUpdateQueryAsSubResourceAttributesFromJSON,
    CatalogVariantUpdateQueryAsSubResourceAttributesFromJSONTyped,
    CatalogVariantUpdateQueryAsSubResourceAttributesToJSON,
} from './CatalogVariantUpdateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface CatalogVariantUpdateQueryAsSubResource
 */
export interface CatalogVariantUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    type: CatalogVariantUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    id: string;
    /**
     * 
     * @type {CatalogVariantUpdateQueryAsSubResourceAttributes}
     * @memberof CatalogVariantUpdateQueryAsSubResource
     */
    attributes: CatalogVariantUpdateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const CatalogVariantUpdateQueryAsSubResourceTypeEnum = {
    CatalogVariant: 'catalog-variant'
} as const;
export type CatalogVariantUpdateQueryAsSubResourceTypeEnum = typeof CatalogVariantUpdateQueryAsSubResourceTypeEnum[keyof typeof CatalogVariantUpdateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CatalogVariantUpdateQueryAsSubResource interface.
 */
export function instanceOfCatalogVariantUpdateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CatalogVariantUpdateQueryAsSubResourceFromJSON(json: any): CatalogVariantUpdateQueryAsSubResource {
    return CatalogVariantUpdateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CatalogVariantUpdateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogVariantUpdateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': CatalogVariantUpdateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function CatalogVariantUpdateQueryAsSubResourceToJSON(value?: CatalogVariantUpdateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': CatalogVariantUpdateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

