/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes } from './CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes';
import {
    CatalogVariantDeleteJobCreateQueryAsSubResourceAttributesFromJSON,
    CatalogVariantDeleteJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    CatalogVariantDeleteJobCreateQueryAsSubResourceAttributesToJSON,
} from './CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface CatalogVariantDeleteJobCreateQueryAsSubResource
 */
export interface CatalogVariantDeleteJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogVariantDeleteJobCreateQueryAsSubResource
     */
    type: CatalogVariantDeleteJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes}
     * @memberof CatalogVariantDeleteJobCreateQueryAsSubResource
     */
    attributes: CatalogVariantDeleteJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const CatalogVariantDeleteJobCreateQueryAsSubResourceTypeEnum = {
    CatalogVariantBulkDeleteJob: 'catalog-variant-bulk-delete-job'
} as const;
export type CatalogVariantDeleteJobCreateQueryAsSubResourceTypeEnum = typeof CatalogVariantDeleteJobCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogVariantDeleteJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CatalogVariantDeleteJobCreateQueryAsSubResource interface.
 */
export function instanceOfCatalogVariantDeleteJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CatalogVariantDeleteJobCreateQueryAsSubResourceFromJSON(json: any): CatalogVariantDeleteJobCreateQueryAsSubResource {
    return CatalogVariantDeleteJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CatalogVariantDeleteJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogVariantDeleteJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': CatalogVariantDeleteJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function CatalogVariantDeleteJobCreateQueryAsSubResourceToJSON(value?: CatalogVariantDeleteJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': CatalogVariantDeleteJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

