/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CatalogItemCreateQueryAsSubResourceAttributes } from './CatalogItemCreateQueryAsSubResourceAttributes';
import {
    CatalogItemCreateQueryAsSubResourceAttributesFromJSON,
    CatalogItemCreateQueryAsSubResourceAttributesFromJSONTyped,
    CatalogItemCreateQueryAsSubResourceAttributesToJSON,
} from './CatalogItemCreateQueryAsSubResourceAttributes';
import type { GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';

/**
 * 
 * @export
 * @interface CatalogItemCreateQueryAsSubResource
 */
export interface CatalogItemCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof CatalogItemCreateQueryAsSubResource
     */
    type: CatalogItemCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {CatalogItemCreateQueryAsSubResourceAttributes}
     * @memberof CatalogItemCreateQueryAsSubResource
     */
    attributes: CatalogItemCreateQueryAsSubResourceAttributes;
    /**
     * 
     * @type {GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof CatalogItemCreateQueryAsSubResource
     */
    relationships?: GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
}


/**
 * @export
 */
export const CatalogItemCreateQueryAsSubResourceTypeEnum = {
    CatalogItem: 'catalog-item'
} as const;
export type CatalogItemCreateQueryAsSubResourceTypeEnum = typeof CatalogItemCreateQueryAsSubResourceTypeEnum[keyof typeof CatalogItemCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the CatalogItemCreateQueryAsSubResource interface.
 */
export function instanceOfCatalogItemCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function CatalogItemCreateQueryAsSubResourceFromJSON(json: any): CatalogItemCreateQueryAsSubResource {
    return CatalogItemCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function CatalogItemCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogItemCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': CatalogItemCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
    };
}

export function CatalogItemCreateQueryAsSubResourceToJSON(value?: CatalogItemCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': CatalogItemCreateQueryAsSubResourceAttributesToJSON(value.attributes),
        'relationships': GetCatalogCategoryCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
    };
}

