/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EventCreateQueryAsSubResourceAttributes } from './EventCreateQueryAsSubResourceAttributes';
import {
    EventCreateQueryAsSubResourceAttributesFromJSON,
    EventCreateQueryAsSubResourceAttributesFromJSONTyped,
    EventCreateQueryAsSubResourceAttributesToJSON,
} from './EventCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface EventCreateQueryAsSubResource
 */
export interface EventCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof EventCreateQueryAsSubResource
     */
    type: EventCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {EventCreateQueryAsSubResourceAttributes}
     * @memberof EventCreateQueryAsSubResource
     */
    attributes: EventCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const EventCreateQueryAsSubResourceTypeEnum = {
    Event: 'event'
} as const;
export type EventCreateQueryAsSubResourceTypeEnum = typeof EventCreateQueryAsSubResourceTypeEnum[keyof typeof EventCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the EventCreateQueryAsSubResource interface.
 */
export function instanceOfEventCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function EventCreateQueryAsSubResourceFromJSON(json: any): EventCreateQueryAsSubResource {
    return EventCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function EventCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': EventCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function EventCreateQueryAsSubResourceToJSON(value?: EventCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': EventCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

