/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FlowUpdateQueryAsSubResource } from './FlowUpdateQueryAsSubResource';
import {
    FlowUpdateQueryAsSubResourceFromJSON,
    FlowUpdateQueryAsSubResourceFromJSONTyped,
    FlowUpdateQueryAsSubResourceToJSON,
} from './FlowUpdateQueryAsSubResource';

/**
 * 
 * @export
 * @interface FlowUpdateQuery
 */
export interface FlowUpdateQuery {
    /**
     * 
     * @type {FlowUpdateQueryAsSubResource}
     * @memberof FlowUpdateQuery
     */
    data: FlowUpdateQueryAsSubResource;
}

/**
 * Check if a given object implements the FlowUpdateQuery interface.
 */
export function instanceOfFlowUpdateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function FlowUpdateQueryFromJSON(json: any): FlowUpdateQuery {
    return FlowUpdateQueryFromJSONTyped(json, false);
}

export function FlowUpdateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlowUpdateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': FlowUpdateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function FlowUpdateQueryToJSON(value?: FlowUpdateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': FlowUpdateQueryAsSubResourceToJSON(value.data),
    };
}

