/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInner } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInner';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInnerFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInnerFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInnerToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInner';

/**
 * 
 * @export
 * @interface GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants
 */
export interface GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants {
    /**
     * 
     * @type {Array<GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInner>}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants
     */
    data: Array<GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInner>;
}

/**
 * Check if a given object implements the GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants interface.
 */
export function instanceOfGetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsFromJSON(json: any): GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants {
    return GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsFromJSONTyped(json, false);
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInnerFromJSON)),
    };
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsToJSON(value?: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariants | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsVariantsDataInnerToJSON)),
    };
}

