/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInner } from './GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInner';
import {
    GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON,
    GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSONTyped,
    GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON,
} from './GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInner';

/**
 * 
 * @export
 * @interface GetCatalogVariantCreateJobResponseCollectionWithIncludedSection
 */
export interface GetCatalogVariantCreateJobResponseCollectionWithIncludedSection {
    /**
     * 
     * @type {Array<GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInner>}
     * @memberof GetCatalogVariantCreateJobResponseCollectionWithIncludedSection
     */
    data: Array<GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetCatalogVariantCreateJobResponseCollectionWithIncludedSection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetCatalogVariantCreateJobResponseCollectionWithIncludedSection interface.
 */
export function instanceOfGetCatalogVariantCreateJobResponseCollectionWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionFromJSON(json: any): GetCatalogVariantCreateJobResponseCollectionWithIncludedSection {
    return GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionFromJSONTyped(json, false);
}

export function GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogVariantCreateJobResponseCollectionWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionToJSON(value?: GetCatalogVariantCreateJobResponseCollectionWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogVariantCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

