/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogVariantUpdateJobResponseWithIncludedSectionData } from './GetCatalogVariantUpdateJobResponseWithIncludedSectionData';
import {
    GetCatalogVariantUpdateJobResponseWithIncludedSectionDataFromJSON,
    GetCatalogVariantUpdateJobResponseWithIncludedSectionDataFromJSONTyped,
    GetCatalogVariantUpdateJobResponseWithIncludedSectionDataToJSON,
} from './GetCatalogVariantUpdateJobResponseWithIncludedSectionData';

/**
 * 
 * @export
 * @interface GetCatalogVariantUpdateJobResponseWithIncludedSection
 */
export interface GetCatalogVariantUpdateJobResponseWithIncludedSection {
    /**
     * 
     * @type {GetCatalogVariantUpdateJobResponseWithIncludedSectionData}
     * @memberof GetCatalogVariantUpdateJobResponseWithIncludedSection
     */
    data: GetCatalogVariantUpdateJobResponseWithIncludedSectionData;
}

/**
 * Check if a given object implements the GetCatalogVariantUpdateJobResponseWithIncludedSection interface.
 */
export function instanceOfGetCatalogVariantUpdateJobResponseWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCatalogVariantUpdateJobResponseWithIncludedSectionFromJSON(json: any): GetCatalogVariantUpdateJobResponseWithIncludedSection {
    return GetCatalogVariantUpdateJobResponseWithIncludedSectionFromJSONTyped(json, false);
}

export function GetCatalogVariantUpdateJobResponseWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogVariantUpdateJobResponseWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCatalogVariantUpdateJobResponseWithIncludedSectionDataFromJSON(json['data']),
    };
}

export function GetCatalogVariantUpdateJobResponseWithIncludedSectionToJSON(value?: GetCatalogVariantUpdateJobResponseWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCatalogVariantUpdateJobResponseWithIncludedSectionDataToJSON(value.data),
    };
}

