/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { IncludedItems } from './IncludedItems';
import {
    IncludedItemsFromJSON,
    IncludedItemsFromJSONTyped,
    IncludedItemsToJSON,
} from './IncludedItems';

/**
 * 
 * @export
 * @interface GetCatalogItemUpdateJobResponseWithIncludedSectionData
 */
export interface GetCatalogItemUpdateJobResponseWithIncludedSectionData {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemUpdateJobResponseWithIncludedSectionData
     */
    type: GetCatalogItemUpdateJobResponseWithIncludedSectionDataTypeEnum;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetCatalogItemUpdateJobResponseWithIncludedSectionData
     */
    attributes: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetCatalogItemUpdateJobResponseWithIncludedSectionData
     */
    relationships?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogItemUpdateJobResponseWithIncludedSectionData
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
    /**
     * 
     * @type {Array<IncludedItems>}
     * @memberof GetCatalogItemUpdateJobResponseWithIncludedSectionData
     */
    included?: Array<IncludedItems>;
}


/**
 * @export
 */
export const GetCatalogItemUpdateJobResponseWithIncludedSectionDataTypeEnum = {
    CatalogItemBulkUpdateJob: 'catalog-item-bulk-update-job'
} as const;
export type GetCatalogItemUpdateJobResponseWithIncludedSectionDataTypeEnum = typeof GetCatalogItemUpdateJobResponseWithIncludedSectionDataTypeEnum[keyof typeof GetCatalogItemUpdateJobResponseWithIncludedSectionDataTypeEnum];


/**
 * Check if a given object implements the GetCatalogItemUpdateJobResponseWithIncludedSectionData interface.
 */
export function instanceOfGetCatalogItemUpdateJobResponseWithIncludedSectionData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogItemUpdateJobResponseWithIncludedSectionDataFromJSON(json: any): GetCatalogItemUpdateJobResponseWithIncludedSectionData {
    return GetCatalogItemUpdateJobResponseWithIncludedSectionDataFromJSONTyped(json, false);
}

export function GetCatalogItemUpdateJobResponseWithIncludedSectionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemUpdateJobResponseWithIncludedSectionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(IncludedItemsFromJSON)),
    };
}

export function GetCatalogItemUpdateJobResponseWithIncludedSectionDataToJSON(value?: GetCatalogItemUpdateJobResponseWithIncludedSectionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'relationships': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(IncludedItemsToJSON)),
    };
}

