/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
 */
export interface GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    imageFullUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    imageThumbnailUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    images?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    customMetadata?: object;
    /**
     * 
     * @type {boolean}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    published?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    updated?: Date;
}

/**
 * Check if a given object implements the GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes interface.
 */
export function instanceOfGetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json: any): GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes {
    return GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json, false);
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'externalId': !exists(json, 'external_id') ? undefined : json['external_id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'imageFullUrl': !exists(json, 'image_full_url') ? undefined : json['image_full_url'],
        'imageThumbnailUrl': !exists(json, 'image_thumbnail_url') ? undefined : json['image_thumbnail_url'],
        'images': !exists(json, 'images') ? undefined : json['images'],
        'customMetadata': !exists(json, 'custom_metadata') ? undefined : json['custom_metadata'],
        'published': !exists(json, 'published') ? undefined : json['published'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
    };
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value?: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external_id': value.externalId,
        'title': value.title,
        'description': value.description,
        'url': value.url,
        'image_full_url': value.imageFullUrl,
        'image_thumbnail_url': value.imageThumbnailUrl,
        'images': value.images,
        'custom_metadata': value.customMetadata,
        'published': value.published,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
    };
}

