/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';

/**
 * 
 * @export
 * @interface GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner
 */
export interface GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner
     */
    type: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner
     */
    attributes: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner
     */
    relationships?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    CatalogItemBulkCreateJob: 'catalog-item-bulk-create-job'
} as const;
export type GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerTypeEnum];


/**
 * Check if a given object implements the GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner interface.
 */
export function instanceOfGetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON(json: any): GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner {
    return GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json, false);
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON(value?: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'relationships': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

