/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetCatalogVariantResponseCollectionDataInner } from './GetCatalogVariantResponseCollectionDataInner';
import {
    GetCatalogVariantResponseCollectionDataInnerFromJSON,
    GetCatalogVariantResponseCollectionDataInnerFromJSONTyped,
    GetCatalogVariantResponseCollectionDataInnerToJSON,
} from './GetCatalogVariantResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetCatalogVariantResponseCollection
 */
export interface GetCatalogVariantResponseCollection {
    /**
     * 
     * @type {Array<GetCatalogVariantResponseCollectionDataInner>}
     * @memberof GetCatalogVariantResponseCollection
     */
    data: Array<GetCatalogVariantResponseCollectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetCatalogVariantResponseCollection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetCatalogVariantResponseCollection interface.
 */
export function instanceOfGetCatalogVariantResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogVariantResponseCollectionFromJSON(json: any): GetCatalogVariantResponseCollection {
    return GetCatalogVariantResponseCollectionFromJSONTyped(json, false);
}

export function GetCatalogVariantResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogVariantResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogVariantResponseCollectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetCatalogVariantResponseCollectionToJSON(value?: GetCatalogVariantResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogVariantResponseCollectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

