/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';

/**
 * 
 * @export
 * @interface GetCatalogItemCreateJobResponseCollectionWithIncludedSection
 */
export interface GetCatalogItemCreateJobResponseCollectionWithIncludedSection {
    /**
     * 
     * @type {Array<GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner>}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSection
     */
    data: Array<GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetCatalogItemCreateJobResponseCollectionWithIncludedSection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetCatalogItemCreateJobResponseCollectionWithIncludedSection interface.
 */
export function instanceOfGetCatalogItemCreateJobResponseCollectionWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionFromJSON(json: any): GetCatalogItemCreateJobResponseCollectionWithIncludedSection {
    return GetCatalogItemCreateJobResponseCollectionWithIncludedSectionFromJSONTyped(json, false);
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemCreateJobResponseCollectionWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetCatalogItemCreateJobResponseCollectionWithIncludedSectionToJSON(value?: GetCatalogItemCreateJobResponseCollectionWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

