/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationships';
import type { IncludedVariants } from './IncludedVariants';
import {
    IncludedVariantsFromJSON,
    IncludedVariantsFromJSONTyped,
    IncludedVariantsToJSON,
} from './IncludedVariants';

/**
 * 
 * @export
 * @interface GetCatalogItemResponseCollectionWithIncludedSectionDataInner
 */
export interface GetCatalogItemResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    type: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    id: string;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    attributes: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    relationships?: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
    /**
     * 
     * @type {Array<IncludedVariants>}
     * @memberof GetCatalogItemResponseCollectionWithIncludedSectionDataInner
     */
    included?: Array<IncludedVariants>;
}


/**
 * @export
 */
export const GetCatalogItemResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    CatalogItem: 'catalog-item'
} as const;
export type GetCatalogItemResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetCatalogItemResponseCollectionWithIncludedSectionDataInnerTypeEnum];


/**
 * Check if a given object implements the GetCatalogItemResponseCollectionWithIncludedSectionDataInner interface.
 */
export function instanceOfGetCatalogItemResponseCollectionWithIncludedSectionDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerFromJSON(json: any): GetCatalogItemResponseCollectionWithIncludedSectionDataInner {
    return GetCatalogItemResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json, false);
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogItemResponseCollectionWithIncludedSectionDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(IncludedVariantsFromJSON)),
    };
}

export function GetCatalogItemResponseCollectionWithIncludedSectionDataInnerToJSON(value?: GetCatalogItemResponseCollectionWithIncludedSectionDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'relationships': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(IncludedVariantsToJSON)),
    };
}

