/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogCategoryItemListResponseCollectionDataInner } from './GetCatalogCategoryItemListResponseCollectionDataInner';
import {
    GetCatalogCategoryItemListResponseCollectionDataInnerFromJSON,
    GetCatalogCategoryItemListResponseCollectionDataInnerFromJSONTyped,
    GetCatalogCategoryItemListResponseCollectionDataInnerToJSON,
} from './GetCatalogCategoryItemListResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetCatalogCategoryItemListResponseCollection
 */
export interface GetCatalogCategoryItemListResponseCollection {
    /**
     * 
     * @type {Array<GetCatalogCategoryItemListResponseCollectionDataInner>}
     * @memberof GetCatalogCategoryItemListResponseCollection
     */
    data: Array<GetCatalogCategoryItemListResponseCollectionDataInner>;
}

/**
 * Check if a given object implements the GetCatalogCategoryItemListResponseCollection interface.
 */
export function instanceOfGetCatalogCategoryItemListResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCatalogCategoryItemListResponseCollectionFromJSON(json: any): GetCatalogCategoryItemListResponseCollection {
    return GetCatalogCategoryItemListResponseCollectionFromJSONTyped(json, false);
}

export function GetCatalogCategoryItemListResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogCategoryItemListResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogCategoryItemListResponseCollectionDataInnerFromJSON)),
    };
}

export function GetCatalogCategoryItemListResponseCollectionToJSON(value?: GetCatalogCategoryItemListResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogCategoryItemListResponseCollectionDataInnerToJSON)),
    };
}

