/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetCatalogVariantDeleteJobResponseCollectionDataInner } from './GetCatalogVariantDeleteJobResponseCollectionDataInner';
import {
    GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSON,
    GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSONTyped,
    GetCatalogVariantDeleteJobResponseCollectionDataInnerToJSON,
} from './GetCatalogVariantDeleteJobResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetCatalogVariantDeleteJobResponseCollection
 */
export interface GetCatalogVariantDeleteJobResponseCollection {
    /**
     * 
     * @type {Array<GetCatalogVariantDeleteJobResponseCollectionDataInner>}
     * @memberof GetCatalogVariantDeleteJobResponseCollection
     */
    data: Array<GetCatalogVariantDeleteJobResponseCollectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetCatalogVariantDeleteJobResponseCollection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetCatalogVariantDeleteJobResponseCollection interface.
 */
export function instanceOfGetCatalogVariantDeleteJobResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetCatalogVariantDeleteJobResponseCollectionFromJSON(json: any): GetCatalogVariantDeleteJobResponseCollection {
    return GetCatalogVariantDeleteJobResponseCollectionFromJSONTyped(json, false);
}

export function GetCatalogVariantDeleteJobResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogVariantDeleteJobResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetCatalogVariantDeleteJobResponseCollectionToJSON(value?: GetCatalogVariantDeleteJobResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetCatalogVariantDeleteJobResponseCollectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

