/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner } from './GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner';
import {
    GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSON,
    GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSONTyped,
    GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerToJSON,
} from './GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner';

/**
 * 
 * @export
 * @interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles
 */
export interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles {
    /**
     * 
     * @type {Array<GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner>}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles
     */
    data: Array<GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner>;
}

/**
 * Check if a given object implements the GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles interface.
 */
export function instanceOfGetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesFromJSON(json: any): GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles {
    return GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesFromJSONTyped(json, false);
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSON)),
    };
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesToJSON(value?: GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfiles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerToJSON)),
    };
}

