/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
 */
export interface GetEventResponseCollectionWithIncludedSectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    metricId: string;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    profileId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    timestamp?: string;
    /**
     * 
     * @type {object}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    eventProperties?: object;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    datetime?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    uuid?: string;
}

/**
 * Check if a given object implements the GetEventResponseCollectionWithIncludedSectionDataInnerAttributes interface.
 */
export function instanceOfGetEventResponseCollectionWithIncludedSectionDataInnerAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "metricId" in value;

    return isInstance;
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json: any): GetEventResponseCollectionWithIncludedSectionDataInnerAttributes {
    return GetEventResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json, false);
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventResponseCollectionWithIncludedSectionDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metricId': json['metric_id'],
        'profileId': !exists(json, 'profile_id') ? undefined : json['profile_id'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'eventProperties': !exists(json, 'event_properties') ? undefined : json['event_properties'],
        'datetime': !exists(json, 'datetime') ? undefined : json['datetime'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
    };
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value?: GetEventResponseCollectionWithIncludedSectionDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metric_id': value.metricId,
        'profile_id': value.profileId,
        'timestamp': value.timestamp,
        'event_properties': value.eventProperties,
        'datetime': value.datetime,
        'uuid': value.uuid,
    };
}

