/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
 */
export interface GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
     */
    type: GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner
     */
    id: string;
}


/**
 * @export
 */
export const GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum = {
    Profile: 'profile'
} as const;
export type GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum = typeof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum[keyof typeof GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerTypeEnum];


/**
 * Check if a given object implements the GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner interface.
 */
export function instanceOfGetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSON(json: any): GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner {
    return GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSONTyped(json, false);
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInnerToJSON(value?: GetEventResponseCollectionWithIncludedSectionDataInnerRelationshipsProfilesDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

