/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetFlowResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetFlowResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetFlowResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes';

/**
 * 
 * @export
 * @interface GetFlowResponseData
 */
export interface GetFlowResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseData
     */
    type: GetFlowResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetFlowResponseData
     */
    id: string;
    /**
     * 
     * @type {GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetFlowResponseData
     */
    attributes: GetFlowResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetFlowResponseData
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const GetFlowResponseDataTypeEnum = {
    Flow: 'flow'
} as const;
export type GetFlowResponseDataTypeEnum = typeof GetFlowResponseDataTypeEnum[keyof typeof GetFlowResponseDataTypeEnum];


/**
 * Check if a given object implements the GetFlowResponseData interface.
 */
export function instanceOfGetFlowResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetFlowResponseDataFromJSON(json: any): GetFlowResponseData {
    return GetFlowResponseDataFromJSONTyped(json, false);
}

export function GetFlowResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetFlowResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function GetFlowResponseDataToJSON(value?: GetFlowResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetFlowResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

