/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    EmailMessageContent,
    instanceOfEmailMessageContent,
    EmailMessageContentFromJSON,
    EmailMessageContentFromJSONTyped,
    EmailMessageContentToJSON,
} from './EmailMessageContent';
import {
    SMSMessageContent,
    instanceOfSMSMessageContent,
    SMSMessageContentFromJSON,
    SMSMessageContentFromJSONTyped,
    SMSMessageContentToJSON,
} from './SMSMessageContent';

/**
 * @type GetFlowMessageResponseCollectionDataInnerAttributesContent
 * 
 * @export
 */
export type GetFlowMessageResponseCollectionDataInnerAttributesContent = EmailMessageContent | SMSMessageContent;

export function GetFlowMessageResponseCollectionDataInnerAttributesContentFromJSON(json: any): GetFlowMessageResponseCollectionDataInnerAttributesContent {
    return GetFlowMessageResponseCollectionDataInnerAttributesContentFromJSONTyped(json, false);
}

export function GetFlowMessageResponseCollectionDataInnerAttributesContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowMessageResponseCollectionDataInnerAttributesContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...EmailMessageContentFromJSONTyped(json, true), ...SMSMessageContentFromJSONTyped(json, true) };
}

export function GetFlowMessageResponseCollectionDataInnerAttributesContentToJSON(value?: GetFlowMessageResponseCollectionDataInnerAttributesContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfEmailMessageContent(value)) {
        return EmailMessageContentToJSON(value as EmailMessageContent);
    }
    if (instanceOfSMSMessageContent(value)) {
        return SMSMessageContentToJSON(value as SMSMessageContent);
    }

    return {};
}

