/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetFlowMessageResponseCollectionDataInnerAttributes } from './GetFlowMessageResponseCollectionDataInnerAttributes';
import {
    GetFlowMessageResponseCollectionDataInnerAttributesFromJSON,
    GetFlowMessageResponseCollectionDataInnerAttributesFromJSONTyped,
    GetFlowMessageResponseCollectionDataInnerAttributesToJSON,
} from './GetFlowMessageResponseCollectionDataInnerAttributes';

/**
 * 
 * @export
 * @interface GetFlowMessageResponseCollectionDataInner
 */
export interface GetFlowMessageResponseCollectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetFlowMessageResponseCollectionDataInner
     */
    type: GetFlowMessageResponseCollectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetFlowMessageResponseCollectionDataInner
     */
    id: string;
    /**
     * 
     * @type {GetFlowMessageResponseCollectionDataInnerAttributes}
     * @memberof GetFlowMessageResponseCollectionDataInner
     */
    attributes: GetFlowMessageResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetFlowMessageResponseCollectionDataInner
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const GetFlowMessageResponseCollectionDataInnerTypeEnum = {
    FlowMessage: 'flow-message'
} as const;
export type GetFlowMessageResponseCollectionDataInnerTypeEnum = typeof GetFlowMessageResponseCollectionDataInnerTypeEnum[keyof typeof GetFlowMessageResponseCollectionDataInnerTypeEnum];


/**
 * Check if a given object implements the GetFlowMessageResponseCollectionDataInner interface.
 */
export function instanceOfGetFlowMessageResponseCollectionDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetFlowMessageResponseCollectionDataInnerFromJSON(json: any): GetFlowMessageResponseCollectionDataInner {
    return GetFlowMessageResponseCollectionDataInnerFromJSONTyped(json, false);
}

export function GetFlowMessageResponseCollectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowMessageResponseCollectionDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetFlowMessageResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function GetFlowMessageResponseCollectionDataInnerToJSON(value?: GetFlowMessageResponseCollectionDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetFlowMessageResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

