/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetFlowActionResponseCollectionDataInner } from './GetFlowActionResponseCollectionDataInner';
import {
    GetFlowActionResponseCollectionDataInnerFromJSON,
    GetFlowActionResponseCollectionDataInnerFromJSONTyped,
    GetFlowActionResponseCollectionDataInnerToJSON,
} from './GetFlowActionResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetFlowActionResponseCollection
 */
export interface GetFlowActionResponseCollection {
    /**
     * 
     * @type {Array<GetFlowActionResponseCollectionDataInner>}
     * @memberof GetFlowActionResponseCollection
     */
    data: Array<GetFlowActionResponseCollectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetFlowActionResponseCollection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetFlowActionResponseCollection interface.
 */
export function instanceOfGetFlowActionResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetFlowActionResponseCollectionFromJSON(json: any): GetFlowActionResponseCollection {
    return GetFlowActionResponseCollectionFromJSONTyped(json, false);
}

export function GetFlowActionResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowActionResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetFlowActionResponseCollectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetFlowActionResponseCollectionToJSON(value?: GetFlowActionResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetFlowActionResponseCollectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

