/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFlowActionResponseWithIncludedSectionData } from './GetFlowActionResponseWithIncludedSectionData';
import {
    GetFlowActionResponseWithIncludedSectionDataFromJSON,
    GetFlowActionResponseWithIncludedSectionDataFromJSONTyped,
    GetFlowActionResponseWithIncludedSectionDataToJSON,
} from './GetFlowActionResponseWithIncludedSectionData';

/**
 * 
 * @export
 * @interface GetFlowActionResponseWithIncludedSection
 */
export interface GetFlowActionResponseWithIncludedSection {
    /**
     * 
     * @type {GetFlowActionResponseWithIncludedSectionData}
     * @memberof GetFlowActionResponseWithIncludedSection
     */
    data: GetFlowActionResponseWithIncludedSectionData;
}

/**
 * Check if a given object implements the GetFlowActionResponseWithIncludedSection interface.
 */
export function instanceOfGetFlowActionResponseWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetFlowActionResponseWithIncludedSectionFromJSON(json: any): GetFlowActionResponseWithIncludedSection {
    return GetFlowActionResponseWithIncludedSectionFromJSONTyped(json, false);
}

export function GetFlowActionResponseWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowActionResponseWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetFlowActionResponseWithIncludedSectionDataFromJSON(json['data']),
    };
}

export function GetFlowActionResponseWithIncludedSectionToJSON(value?: GetFlowActionResponseWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetFlowActionResponseWithIncludedSectionDataToJSON(value.data),
    };
}

