/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner } from './GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner';
import {
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSON,
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSONTyped,
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerToJSON,
} from './GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner';

/**
 * 
 * @export
 * @interface GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages
 */
export interface GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages {
    /**
     * 
     * @type {Array<GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner>}
     * @memberof GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages
     */
    data: Array<GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner>;
}

/**
 * Check if a given object implements the GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages interface.
 */
export function instanceOfGetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesFromJSON(json: any): GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages {
    return GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesFromJSONTyped(json, false);
}

export function GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSON)),
    };
}

export function GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesToJSON(value?: GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerToJSON)),
    };
}

