/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFlowActionResponseCollectionDataInner } from './GetFlowActionResponseCollectionDataInner';
import {
    GetFlowActionResponseCollectionDataInnerFromJSON,
    GetFlowActionResponseCollectionDataInnerFromJSONTyped,
    GetFlowActionResponseCollectionDataInnerToJSON,
} from './GetFlowActionResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetFlowActionResponse
 */
export interface GetFlowActionResponse {
    /**
     * 
     * @type {GetFlowActionResponseCollectionDataInner}
     * @memberof GetFlowActionResponse
     */
    data: GetFlowActionResponseCollectionDataInner;
}

/**
 * Check if a given object implements the GetFlowActionResponse interface.
 */
export function instanceOfGetFlowActionResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetFlowActionResponseFromJSON(json: any): GetFlowActionResponse {
    return GetFlowActionResponseFromJSONTyped(json, false);
}

export function GetFlowActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowActionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetFlowActionResponseCollectionDataInnerFromJSON(json['data']),
    };
}

export function GetFlowActionResponseToJSON(value?: GetFlowActionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetFlowActionResponseCollectionDataInnerToJSON(value.data),
    };
}

