/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner } from './GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner';
import {
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSON,
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSONTyped,
    GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerToJSON,
} from './GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner';

/**
 * 
 * @export
 * @interface GetFlowActionFlowMessageRelationshipResponseCollection
 */
export interface GetFlowActionFlowMessageRelationshipResponseCollection {
    /**
     * 
     * @type {GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner}
     * @memberof GetFlowActionFlowMessageRelationshipResponseCollection
     */
    data: GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInner;
}

/**
 * Check if a given object implements the GetFlowActionFlowMessageRelationshipResponseCollection interface.
 */
export function instanceOfGetFlowActionFlowMessageRelationshipResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetFlowActionFlowMessageRelationshipResponseCollectionFromJSON(json: any): GetFlowActionFlowMessageRelationshipResponseCollection {
    return GetFlowActionFlowMessageRelationshipResponseCollectionFromJSONTyped(json, false);
}

export function GetFlowActionFlowMessageRelationshipResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowActionFlowMessageRelationshipResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerFromJSON(json['data']),
    };
}

export function GetFlowActionFlowMessageRelationshipResponseCollectionToJSON(value?: GetFlowActionFlowMessageRelationshipResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetFlowActionResponseWithIncludedSectionDataRelationshipsFlowMessagesDataInnerToJSON(value.data),
    };
}

