/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowAction } from './GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowAction';
import {
    GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowActionFromJSON,
    GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowActionFromJSONTyped,
    GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowActionToJSON,
} from './GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowAction';

/**
 * 
 * @export
 * @interface GetFlowMessageResponseWithIncludedSectionDataRelationships
 */
export interface GetFlowMessageResponseWithIncludedSectionDataRelationships {
    /**
     * 
     * @type {GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowAction}
     * @memberof GetFlowMessageResponseWithIncludedSectionDataRelationships
     */
    flowAction?: GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowAction;
}

/**
 * Check if a given object implements the GetFlowMessageResponseWithIncludedSectionDataRelationships interface.
 */
export function instanceOfGetFlowMessageResponseWithIncludedSectionDataRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetFlowMessageResponseWithIncludedSectionDataRelationshipsFromJSON(json: any): GetFlowMessageResponseWithIncludedSectionDataRelationships {
    return GetFlowMessageResponseWithIncludedSectionDataRelationshipsFromJSONTyped(json, false);
}

export function GetFlowMessageResponseWithIncludedSectionDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFlowMessageResponseWithIncludedSectionDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flowAction': !exists(json, 'flow-action') ? undefined : GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowActionFromJSON(json['flow-action']),
    };
}

export function GetFlowMessageResponseWithIncludedSectionDataRelationshipsToJSON(value?: GetFlowMessageResponseWithIncludedSectionDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flow-action': GetFlowMessageResponseWithIncludedSectionDataRelationshipsFlowActionToJSON(value.flowAction),
    };
}

