/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTags } from './GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTags';
import {
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTagsFromJSON,
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTagsFromJSONTyped,
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTagsToJSON,
} from './GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTags';

/**
 * 
 * @export
 * @interface GetListResponseCollectionWithIncludedSectionDataInnerRelationships
 */
export interface GetListResponseCollectionWithIncludedSectionDataInnerRelationships {
    /**
     * 
     * @type {GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTags}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInnerRelationships
     */
    tags?: GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTags;
}

/**
 * Check if a given object implements the GetListResponseCollectionWithIncludedSectionDataInnerRelationships interface.
 */
export function instanceOfGetListResponseCollectionWithIncludedSectionDataInnerRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json: any): GetListResponseCollectionWithIncludedSectionDataInnerRelationships {
    return GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped(json, false);
}

export function GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListResponseCollectionWithIncludedSectionDataInnerRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTagsFromJSON(json['tags']),
    };
}

export function GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value?: GetListResponseCollectionWithIncludedSectionDataInnerRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsTagsToJSON(value.tags),
    };
}

