/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetListResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetListResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetListResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetListResponseCollectionWithIncludedSectionDataInnerAttributes';
import type { GetListResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetListResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetListResponseCollectionWithIncludedSectionDataInnerRelationships';
import type { IncludedTags } from './IncludedTags';
import {
    IncludedTagsFromJSON,
    IncludedTagsFromJSONTyped,
    IncludedTagsToJSON,
} from './IncludedTags';

/**
 * 
 * @export
 * @interface GetListResponseCollectionWithIncludedSectionDataInner
 */
export interface GetListResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    type: GetListResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    id: string;
    /**
     * 
     * @type {GetListResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    attributes: GetListResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetListResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    relationships?: GetListResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
    /**
     * 
     * @type {Array<IncludedTags>}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInner
     */
    included?: Array<IncludedTags>;
}


/**
 * @export
 */
export const GetListResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    List: 'list'
} as const;
export type GetListResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetListResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetListResponseCollectionWithIncludedSectionDataInnerTypeEnum];


/**
 * Check if a given object implements the GetListResponseCollectionWithIncludedSectionDataInner interface.
 */
export function instanceOfGetListResponseCollectionWithIncludedSectionDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetListResponseCollectionWithIncludedSectionDataInnerFromJSON(json: any): GetListResponseCollectionWithIncludedSectionDataInner {
    return GetListResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json, false);
}

export function GetListResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListResponseCollectionWithIncludedSectionDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(IncludedTagsFromJSON)),
    };
}

export function GetListResponseCollectionWithIncludedSectionDataInnerToJSON(value?: GetListResponseCollectionWithIncludedSectionDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetListResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'relationships': GetListResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(IncludedTagsToJSON)),
    };
}

