/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListResponseCollectionWithIncludedSectionDataInnerAttributes
 */
export interface GetListResponseCollectionWithIncludedSectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetListResponseCollectionWithIncludedSectionDataInnerAttributes
     */
    updated?: Date;
}

/**
 * Check if a given object implements the GetListResponseCollectionWithIncludedSectionDataInnerAttributes interface.
 */
export function instanceOfGetListResponseCollectionWithIncludedSectionDataInnerAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json: any): GetListResponseCollectionWithIncludedSectionDataInnerAttributes {
    return GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json, false);
}

export function GetListResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListResponseCollectionWithIncludedSectionDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
    };
}

export function GetListResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value?: GetListResponseCollectionWithIncludedSectionDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
    };
}

