/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetListResponseCollectionDataInner } from './GetListResponseCollectionDataInner';
import {
    GetListResponseCollectionDataInnerFromJSON,
    GetListResponseCollectionDataInnerFromJSONTyped,
    GetListResponseCollectionDataInnerToJSON,
} from './GetListResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetListResponseCollection
 */
export interface GetListResponseCollection {
    /**
     * 
     * @type {Array<GetListResponseCollectionDataInner>}
     * @memberof GetListResponseCollection
     */
    data: Array<GetListResponseCollectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetListResponseCollection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetListResponseCollection interface.
 */
export function instanceOfGetListResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetListResponseCollectionFromJSON(json: any): GetListResponseCollection {
    return GetListResponseCollectionFromJSONTyped(json, false);
}

export function GetListResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetListResponseCollectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetListResponseCollectionToJSON(value?: GetListResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetListResponseCollectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

