/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfileLocation } from './ProfileLocation';
import {
    ProfileLocationFromJSON,
    ProfileLocationFromJSONTyped,
    ProfileLocationToJSON,
} from './ProfileLocation';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionDataInnerAttributes
 */
export interface GetProfileResponseCollectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    anonymousId?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    image?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    updated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    lastEventDate?: Date;
    /**
     * 
     * @type {ProfileLocation}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    location?: ProfileLocation;
    /**
     * 
     * @type {object}
     * @memberof GetProfileResponseCollectionDataInnerAttributes
     */
    properties?: object;
}

/**
 * Check if a given object implements the GetProfileResponseCollectionDataInnerAttributes interface.
 */
export function instanceOfGetProfileResponseCollectionDataInnerAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetProfileResponseCollectionDataInnerAttributesFromJSON(json: any): GetProfileResponseCollectionDataInnerAttributes {
    return GetProfileResponseCollectionDataInnerAttributesFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollectionDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'externalId': !exists(json, 'external_id') ? undefined : json['external_id'],
        'anonymousId': !exists(json, 'anonymous_id') ? undefined : json['anonymous_id'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
        'lastEventDate': !exists(json, 'last_event_date') ? undefined : (new Date(json['last_event_date'])),
        'location': !exists(json, 'location') ? undefined : ProfileLocationFromJSON(json['location']),
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
    };
}

export function GetProfileResponseCollectionDataInnerAttributesToJSON(value?: GetProfileResponseCollectionDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'phone_number': value.phoneNumber,
        'external_id': value.externalId,
        'anonymous_id': value.anonymousId,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'organization': value.organization,
        'title': value.title,
        'image': value.image,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
        'last_event_date': value.lastEventDate === undefined ? undefined : (value.lastEventDate.toISOString()),
        'location': ProfileLocationToJSON(value.location),
        'properties': value.properties,
    };
}

