/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetProfileResponseCollectionDataInner } from './GetProfileResponseCollectionDataInner';
import {
    GetProfileResponseCollectionDataInnerFromJSON,
    GetProfileResponseCollectionDataInnerFromJSONTyped,
    GetProfileResponseCollectionDataInnerToJSON,
} from './GetProfileResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface GetProfileResponseCollection
 */
export interface GetProfileResponseCollection {
    /**
     * 
     * @type {Array<GetProfileResponseCollectionDataInner>}
     * @memberof GetProfileResponseCollection
     */
    data: Array<GetProfileResponseCollectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetProfileResponseCollection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetProfileResponseCollection interface.
 */
export function instanceOfGetProfileResponseCollection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetProfileResponseCollectionFromJSON(json: any): GetProfileResponseCollection {
    return GetProfileResponseCollectionFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetProfileResponseCollectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetProfileResponseCollectionToJSON(value?: GetProfileResponseCollection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetProfileResponseCollectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

