/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetProfileResponseCollectionDataInnerAttributes } from './GetProfileResponseCollectionDataInnerAttributes';
import {
    GetProfileResponseCollectionDataInnerAttributesFromJSON,
    GetProfileResponseCollectionDataInnerAttributesFromJSONTyped,
    GetProfileResponseCollectionDataInnerAttributesToJSON,
} from './GetProfileResponseCollectionDataInnerAttributes';
import type { GetProfileResponseCollectionWithIncludedSectionDataInnerRelationships } from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationships';
import {
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSONTyped,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON,
} from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationships';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionWithIncludedSectionDataInner
 */
export interface GetProfileResponseCollectionWithIncludedSectionDataInner {
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInner
     */
    type: GetProfileResponseCollectionWithIncludedSectionDataInnerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInner
     */
    id: string;
    /**
     * 
     * @type {GetProfileResponseCollectionDataInnerAttributes}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInner
     */
    attributes: GetProfileResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetProfileResponseCollectionWithIncludedSectionDataInnerRelationships}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInner
     */
    relationships?: GetProfileResponseCollectionWithIncludedSectionDataInnerRelationships;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInner
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const GetProfileResponseCollectionWithIncludedSectionDataInnerTypeEnum = {
    Profile: 'profile'
} as const;
export type GetProfileResponseCollectionWithIncludedSectionDataInnerTypeEnum = typeof GetProfileResponseCollectionWithIncludedSectionDataInnerTypeEnum[keyof typeof GetProfileResponseCollectionWithIncludedSectionDataInnerTypeEnum];


/**
 * Check if a given object implements the GetProfileResponseCollectionWithIncludedSectionDataInner interface.
 */
export function instanceOfGetProfileResponseCollectionWithIncludedSectionDataInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSON(json: any): GetProfileResponseCollectionWithIncludedSectionDataInner {
    return GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollectionWithIncludedSectionDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetProfileResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsFromJSON(json['relationships']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerToJSON(value?: GetProfileResponseCollectionWithIncludedSectionDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetProfileResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'relationships': GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsToJSON(value.relationships),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

