/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInner } from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInner';
import {
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInnerFromJSON,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInnerFromJSONTyped,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInnerToJSON,
} from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInner';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists
 */
export interface GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists {
    /**
     * 
     * @type {Array<GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInner>}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists
     */
    data: Array<GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInner>;
}

/**
 * Check if a given object implements the GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists interface.
 */
export function instanceOfGetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsFromJSON(json: any): GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists {
    return GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInnerFromJSON)),
    };
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsToJSON(value?: GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsLists | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsListsDataInnerToJSON)),
    };
}

