/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    IncludedLists,
    instanceOfIncludedLists,
    IncludedListsFromJSON,
    IncludedListsFromJSONTyped,
    IncludedListsToJSON,
} from './IncludedLists';
import {
    IncludedSegments,
    instanceOfIncludedSegments,
    IncludedSegmentsFromJSON,
    IncludedSegmentsFromJSONTyped,
    IncludedSegmentsToJSON,
} from './IncludedSegments';

/**
 * @type GetProfileResponseWithIncludedSectionDataIncludedInner
 * 
 * @export
 */
export type GetProfileResponseWithIncludedSectionDataIncludedInner = IncludedLists | IncludedSegments;

export function GetProfileResponseWithIncludedSectionDataIncludedInnerFromJSON(json: any): GetProfileResponseWithIncludedSectionDataIncludedInner {
    return GetProfileResponseWithIncludedSectionDataIncludedInnerFromJSONTyped(json, false);
}

export function GetProfileResponseWithIncludedSectionDataIncludedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseWithIncludedSectionDataIncludedInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...IncludedListsFromJSONTyped(json, true), ...IncludedSegmentsFromJSONTyped(json, true) };
}

export function GetProfileResponseWithIncludedSectionDataIncludedInnerToJSON(value?: GetProfileResponseWithIncludedSectionDataIncludedInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfIncludedLists(value)) {
        return IncludedListsToJSON(value as IncludedLists);
    }
    if (instanceOfIncludedSegments(value)) {
        return IncludedSegmentsToJSON(value as IncludedSegments);
    }

    return {};
}

