/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInner } from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInner';
import {
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInnerFromJSON,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInnerFromJSONTyped,
    GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInnerToJSON,
} from './GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInner';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments
 */
export interface GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments {
    /**
     * 
     * @type {Array<GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInner>}
     * @memberof GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments
     */
    data: Array<GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInner>;
}

/**
 * Check if a given object implements the GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments interface.
 */
export function instanceOfGetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsFromJSON(json: any): GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments {
    return GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInnerFromJSON)),
    };
}

export function GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsToJSON(value?: GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegments | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerRelationshipsSegmentsDataInnerToJSON)),
    };
}

