/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetProfileResponseCollectionWithIncludedSectionDataInner } from './GetProfileResponseCollectionWithIncludedSectionDataInner';
import {
    GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSON,
    GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSONTyped,
    GetProfileResponseCollectionWithIncludedSectionDataInnerToJSON,
} from './GetProfileResponseCollectionWithIncludedSectionDataInner';

/**
 * 
 * @export
 * @interface GetProfileResponseCollectionWithIncludedSection
 */
export interface GetProfileResponseCollectionWithIncludedSection {
    /**
     * 
     * @type {Array<GetProfileResponseCollectionWithIncludedSectionDataInner>}
     * @memberof GetProfileResponseCollectionWithIncludedSection
     */
    data: Array<GetProfileResponseCollectionWithIncludedSectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetProfileResponseCollectionWithIncludedSection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetProfileResponseCollectionWithIncludedSection interface.
 */
export function instanceOfGetProfileResponseCollectionWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetProfileResponseCollectionWithIncludedSectionFromJSON(json: any): GetProfileResponseCollectionWithIncludedSection {
    return GetProfileResponseCollectionWithIncludedSectionFromJSONTyped(json, false);
}

export function GetProfileResponseCollectionWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProfileResponseCollectionWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetProfileResponseCollectionWithIncludedSectionToJSON(value?: GetProfileResponseCollectionWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetProfileResponseCollectionWithIncludedSectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

