/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionLinks';
import type { GetSegmentResponseCollectionWithIncludedSectionDataInner } from './GetSegmentResponseCollectionWithIncludedSectionDataInner';
import {
    GetSegmentResponseCollectionWithIncludedSectionDataInnerFromJSON,
    GetSegmentResponseCollectionWithIncludedSectionDataInnerFromJSONTyped,
    GetSegmentResponseCollectionWithIncludedSectionDataInnerToJSON,
} from './GetSegmentResponseCollectionWithIncludedSectionDataInner';

/**
 * 
 * @export
 * @interface GetSegmentResponseCollectionWithIncludedSection
 */
export interface GetSegmentResponseCollectionWithIncludedSection {
    /**
     * 
     * @type {Array<GetSegmentResponseCollectionWithIncludedSectionDataInner>}
     * @memberof GetSegmentResponseCollectionWithIncludedSection
     */
    data: Array<GetSegmentResponseCollectionWithIncludedSectionDataInner>;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionLinks}
     * @memberof GetSegmentResponseCollectionWithIncludedSection
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionLinks;
}

/**
 * Check if a given object implements the GetSegmentResponseCollectionWithIncludedSection interface.
 */
export function instanceOfGetSegmentResponseCollectionWithIncludedSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function GetSegmentResponseCollectionWithIncludedSectionFromJSON(json: any): GetSegmentResponseCollectionWithIncludedSection {
    return GetSegmentResponseCollectionWithIncludedSectionFromJSONTyped(json, false);
}

export function GetSegmentResponseCollectionWithIncludedSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSegmentResponseCollectionWithIncludedSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetSegmentResponseCollectionWithIncludedSectionDataInnerFromJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksFromJSON(json['links']),
    };
}

export function GetSegmentResponseCollectionWithIncludedSectionToJSON(value?: GetSegmentResponseCollectionWithIncludedSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetSegmentResponseCollectionWithIncludedSectionDataInnerToJSON)),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionLinksToJSON(value.links),
    };
}

