/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTemplateResponseCollectionDataInnerAttributes
 */
export interface GetTemplateResponseCollectionDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    companyId: string;
    /**
     * 
     * @type {string}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    editorType: string;
    /**
     * 
     * @type {string}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    html: string;
    /**
     * 
     * @type {string}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetTemplateResponseCollectionDataInnerAttributes
     */
    updated?: Date;
}

/**
 * Check if a given object implements the GetTemplateResponseCollectionDataInnerAttributes interface.
 */
export function instanceOfGetTemplateResponseCollectionDataInnerAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "companyId" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "editorType" in value;
    isInstance = isInstance && "html" in value;

    return isInstance;
}

export function GetTemplateResponseCollectionDataInnerAttributesFromJSON(json: any): GetTemplateResponseCollectionDataInnerAttributes {
    return GetTemplateResponseCollectionDataInnerAttributesFromJSONTyped(json, false);
}

export function GetTemplateResponseCollectionDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTemplateResponseCollectionDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'companyId': json['company_id'],
        'name': json['name'],
        'editorType': json['editor_type'],
        'html': json['html'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
    };
}

export function GetTemplateResponseCollectionDataInnerAttributesToJSON(value?: GetTemplateResponseCollectionDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company_id': value.companyId,
        'name': value.name,
        'editor_type': value.editorType,
        'html': value.html,
        'text': value.text,
        'created': value.created === undefined ? undefined : (value.created.toISOString()),
        'updated': value.updated === undefined ? undefined : (value.updated.toISOString()),
    };
}

