/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetMetricResponseCollectionDataInnerAttributes } from './GetMetricResponseCollectionDataInnerAttributes';
import {
    GetMetricResponseCollectionDataInnerAttributesFromJSON,
    GetMetricResponseCollectionDataInnerAttributesFromJSONTyped,
    GetMetricResponseCollectionDataInnerAttributesToJSON,
} from './GetMetricResponseCollectionDataInnerAttributes';

/**
 * 
 * @export
 * @interface IncludedMetrics
 */
export interface IncludedMetrics {
    /**
     * 
     * @type {string}
     * @memberof IncludedMetrics
     */
    type: IncludedMetricsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedMetrics
     */
    id: string;
    /**
     * 
     * @type {GetMetricResponseCollectionDataInnerAttributes}
     * @memberof IncludedMetrics
     */
    attributes: GetMetricResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedMetrics
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const IncludedMetricsTypeEnum = {
    Metric: 'metric'
} as const;
export type IncludedMetricsTypeEnum = typeof IncludedMetricsTypeEnum[keyof typeof IncludedMetricsTypeEnum];


/**
 * Check if a given object implements the IncludedMetrics interface.
 */
export function instanceOfIncludedMetrics(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function IncludedMetricsFromJSON(json: any): IncludedMetrics {
    return IncludedMetricsFromJSONTyped(json, false);
}

export function IncludedMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetMetricResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function IncludedMetricsToJSON(value?: IncludedMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetMetricResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

