/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetProfileResponseCollectionDataInnerAttributes } from './GetProfileResponseCollectionDataInnerAttributes';
import {
    GetProfileResponseCollectionDataInnerAttributesFromJSON,
    GetProfileResponseCollectionDataInnerAttributesFromJSONTyped,
    GetProfileResponseCollectionDataInnerAttributesToJSON,
} from './GetProfileResponseCollectionDataInnerAttributes';

/**
 * 
 * @export
 * @interface IncludedProfile
 */
export interface IncludedProfile {
    /**
     * 
     * @type {string}
     * @memberof IncludedProfile
     */
    type: IncludedProfileTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedProfile
     */
    id: string;
    /**
     * 
     * @type {GetProfileResponseCollectionDataInnerAttributes}
     * @memberof IncludedProfile
     */
    attributes: GetProfileResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedProfile
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const IncludedProfileTypeEnum = {
    Profile: 'profile'
} as const;
export type IncludedProfileTypeEnum = typeof IncludedProfileTypeEnum[keyof typeof IncludedProfileTypeEnum];


/**
 * Check if a given object implements the IncludedProfile interface.
 */
export function instanceOfIncludedProfile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function IncludedProfileFromJSON(json: any): IncludedProfile {
    return IncludedProfileFromJSONTyped(json, false);
}

export function IncludedProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetProfileResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function IncludedProfileToJSON(value?: IncludedProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetProfileResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

