/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { GetFlowActionResponseCollectionDataInnerAttributes } from './GetFlowActionResponseCollectionDataInnerAttributes';
import {
    GetFlowActionResponseCollectionDataInnerAttributesFromJSON,
    GetFlowActionResponseCollectionDataInnerAttributesFromJSONTyped,
    GetFlowActionResponseCollectionDataInnerAttributesToJSON,
} from './GetFlowActionResponseCollectionDataInnerAttributes';

/**
 * 
 * @export
 * @interface IncludedFlowAction
 */
export interface IncludedFlowAction {
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowAction
     */
    type: IncludedFlowActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedFlowAction
     */
    id: string;
    /**
     * 
     * @type {GetFlowActionResponseCollectionDataInnerAttributes}
     * @memberof IncludedFlowAction
     */
    attributes: GetFlowActionResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedFlowAction
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const IncludedFlowActionTypeEnum = {
    FlowAction: 'flow-action'
} as const;
export type IncludedFlowActionTypeEnum = typeof IncludedFlowActionTypeEnum[keyof typeof IncludedFlowActionTypeEnum];


/**
 * Check if a given object implements the IncludedFlowAction interface.
 */
export function instanceOfIncludedFlowAction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function IncludedFlowActionFromJSON(json: any): IncludedFlowAction {
    return IncludedFlowActionFromJSONTyped(json, false);
}

export function IncludedFlowActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedFlowAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetFlowActionResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function IncludedFlowActionToJSON(value?: IncludedFlowAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetFlowActionResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

