/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogCategoryResponseCollectionDataInnerAttributes } from './GetCatalogCategoryResponseCollectionDataInnerAttributes';
import {
    GetCatalogCategoryResponseCollectionDataInnerAttributesFromJSON,
    GetCatalogCategoryResponseCollectionDataInnerAttributesFromJSONTyped,
    GetCatalogCategoryResponseCollectionDataInnerAttributesToJSON,
} from './GetCatalogCategoryResponseCollectionDataInnerAttributes';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';

/**
 * 
 * @export
 * @interface IncludedCategories
 */
export interface IncludedCategories {
    /**
     * 
     * @type {string}
     * @memberof IncludedCategories
     */
    type: IncludedCategoriesTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedCategories
     */
    id: string;
    /**
     * 
     * @type {GetCatalogCategoryResponseCollectionDataInnerAttributes}
     * @memberof IncludedCategories
     */
    attributes: GetCatalogCategoryResponseCollectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedCategories
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const IncludedCategoriesTypeEnum = {
    CatalogCategory: 'catalog-category'
} as const;
export type IncludedCategoriesTypeEnum = typeof IncludedCategoriesTypeEnum[keyof typeof IncludedCategoriesTypeEnum];


/**
 * Check if a given object implements the IncludedCategories interface.
 */
export function instanceOfIncludedCategories(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function IncludedCategoriesFromJSON(json: any): IncludedCategories {
    return IncludedCategoriesFromJSONTyped(json, false);
}

export function IncludedCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedCategories {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetCatalogCategoryResponseCollectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function IncludedCategoriesToJSON(value?: IncludedCategories | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetCatalogCategoryResponseCollectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

