/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';

/**
 * 
 * @export
 * @interface IncludedItems
 */
export interface IncludedItems {
    /**
     * 
     * @type {string}
     * @memberof IncludedItems
     */
    type: IncludedItemsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof IncludedItems
     */
    id: string;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes}
     * @memberof IncludedItems
     */
    attributes: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof IncludedItems
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const IncludedItemsTypeEnum = {
    CatalogItem: 'catalog-item'
} as const;
export type IncludedItemsTypeEnum = typeof IncludedItemsTypeEnum[keyof typeof IncludedItemsTypeEnum];


/**
 * Check if a given object implements the IncludedItems interface.
 */
export function instanceOfIncludedItems(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function IncludedItemsFromJSON(json: any): IncludedItems {
    return IncludedItemsFromJSONTyped(json, false);
}

export function IncludedItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncludedItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function IncludedItemsToJSON(value?: IncludedItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

