/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListCreateQueryAsSubResource } from './ListCreateQueryAsSubResource';
import {
    ListCreateQueryAsSubResourceFromJSON,
    ListCreateQueryAsSubResourceFromJSONTyped,
    ListCreateQueryAsSubResourceToJSON,
} from './ListCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface ListCreateQuery
 */
export interface ListCreateQuery {
    /**
     * 
     * @type {ListCreateQueryAsSubResource}
     * @memberof ListCreateQuery
     */
    data: ListCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the ListCreateQuery interface.
 */
export function instanceOfListCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ListCreateQueryFromJSON(json: any): ListCreateQuery {
    return ListCreateQueryFromJSONTyped(json, false);
}

export function ListCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ListCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function ListCreateQueryToJSON(value?: ListCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ListCreateQueryAsSubResourceToJSON(value.data),
    };
}

