/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListCreateQueryAsSubResourceAttributes } from './ListCreateQueryAsSubResourceAttributes';
import {
    ListCreateQueryAsSubResourceAttributesFromJSON,
    ListCreateQueryAsSubResourceAttributesFromJSONTyped,
    ListCreateQueryAsSubResourceAttributesToJSON,
} from './ListCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface ListPartialUpdateQueryAsSubResource
 */
export interface ListPartialUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof ListPartialUpdateQueryAsSubResource
     */
    type: ListPartialUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ListPartialUpdateQueryAsSubResource
     */
    id: string;
    /**
     * 
     * @type {ListCreateQueryAsSubResourceAttributes}
     * @memberof ListPartialUpdateQueryAsSubResource
     */
    attributes: ListCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const ListPartialUpdateQueryAsSubResourceTypeEnum = {
    List: 'list'
} as const;
export type ListPartialUpdateQueryAsSubResourceTypeEnum = typeof ListPartialUpdateQueryAsSubResourceTypeEnum[keyof typeof ListPartialUpdateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the ListPartialUpdateQueryAsSubResource interface.
 */
export function instanceOfListPartialUpdateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function ListPartialUpdateQueryAsSubResourceFromJSON(json: any): ListPartialUpdateQueryAsSubResource {
    return ListPartialUpdateQueryAsSubResourceFromJSONTyped(json, false);
}

export function ListPartialUpdateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPartialUpdateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ListCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function ListPartialUpdateQueryAsSubResourceToJSON(value?: ListPartialUpdateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': ListCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

