/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricAggregateRowDTO
 */
export interface MetricAggregateRowDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof MetricAggregateRowDTO
     */
    dimensions: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof MetricAggregateRowDTO
     */
    measurements: object;
}

/**
 * Check if a given object implements the MetricAggregateRowDTO interface.
 */
export function instanceOfMetricAggregateRowDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dimensions" in value;
    isInstance = isInstance && "measurements" in value;

    return isInstance;
}

export function MetricAggregateRowDTOFromJSON(json: any): MetricAggregateRowDTO {
    return MetricAggregateRowDTOFromJSONTyped(json, false);
}

export function MetricAggregateRowDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricAggregateRowDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dimensions': json['dimensions'],
        'measurements': json['measurements'],
    };
}

export function MetricAggregateRowDTOToJSON(value?: MetricAggregateRowDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dimensions': value.dimensions,
        'measurements': value.measurements,
    };
}

