/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OnsiteSubscriptionCreateQueryAsSubResource } from './OnsiteSubscriptionCreateQueryAsSubResource';
import {
    OnsiteSubscriptionCreateQueryAsSubResourceFromJSON,
    OnsiteSubscriptionCreateQueryAsSubResourceFromJSONTyped,
    OnsiteSubscriptionCreateQueryAsSubResourceToJSON,
} from './OnsiteSubscriptionCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface OnsiteSubscriptionCreateQuery
 */
export interface OnsiteSubscriptionCreateQuery {
    /**
     * 
     * @type {OnsiteSubscriptionCreateQueryAsSubResource}
     * @memberof OnsiteSubscriptionCreateQuery
     */
    data: OnsiteSubscriptionCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the OnsiteSubscriptionCreateQuery interface.
 */
export function instanceOfOnsiteSubscriptionCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function OnsiteSubscriptionCreateQueryFromJSON(json: any): OnsiteSubscriptionCreateQuery {
    return OnsiteSubscriptionCreateQueryFromJSONTyped(json, false);
}

export function OnsiteSubscriptionCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteSubscriptionCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': OnsiteSubscriptionCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function OnsiteSubscriptionCreateQueryToJSON(value?: OnsiteSubscriptionCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': OnsiteSubscriptionCreateQueryAsSubResourceToJSON(value.data),
    };
}

