/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OnsiteSubscriptionCreateQueryAsSubResourceAttributes } from './OnsiteSubscriptionCreateQueryAsSubResourceAttributes';
import {
    OnsiteSubscriptionCreateQueryAsSubResourceAttributesFromJSON,
    OnsiteSubscriptionCreateQueryAsSubResourceAttributesFromJSONTyped,
    OnsiteSubscriptionCreateQueryAsSubResourceAttributesToJSON,
} from './OnsiteSubscriptionCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface OnsiteSubscriptionCreateQueryAsSubResource
 */
export interface OnsiteSubscriptionCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResource
     */
    type: OnsiteSubscriptionCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {OnsiteSubscriptionCreateQueryAsSubResourceAttributes}
     * @memberof OnsiteSubscriptionCreateQueryAsSubResource
     */
    attributes: OnsiteSubscriptionCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const OnsiteSubscriptionCreateQueryAsSubResourceTypeEnum = {
    Subscription: 'subscription'
} as const;
export type OnsiteSubscriptionCreateQueryAsSubResourceTypeEnum = typeof OnsiteSubscriptionCreateQueryAsSubResourceTypeEnum[keyof typeof OnsiteSubscriptionCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the OnsiteSubscriptionCreateQueryAsSubResource interface.
 */
export function instanceOfOnsiteSubscriptionCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function OnsiteSubscriptionCreateQueryAsSubResourceFromJSON(json: any): OnsiteSubscriptionCreateQueryAsSubResource {
    return OnsiteSubscriptionCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function OnsiteSubscriptionCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnsiteSubscriptionCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': OnsiteSubscriptionCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function OnsiteSubscriptionCreateQueryAsSubResourceToJSON(value?: OnsiteSubscriptionCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': OnsiteSubscriptionCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

