/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner } from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner';
import {
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSONTyped,
    GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON,
} from './GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner';

/**
 * 
 * @export
 * @interface PostCatalogItemCreateJobResponse
 */
export interface PostCatalogItemCreateJobResponse {
    /**
     * 
     * @type {GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner}
     * @memberof PostCatalogItemCreateJobResponse
     */
    data: GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInner;
}

/**
 * Check if a given object implements the PostCatalogItemCreateJobResponse interface.
 */
export function instanceOfPostCatalogItemCreateJobResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostCatalogItemCreateJobResponseFromJSON(json: any): PostCatalogItemCreateJobResponse {
    return PostCatalogItemCreateJobResponseFromJSONTyped(json, false);
}

export function PostCatalogItemCreateJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCatalogItemCreateJobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerFromJSON(json['data']),
    };
}

export function PostCatalogItemCreateJobResponseToJSON(value?: PostCatalogItemCreateJobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCatalogItemCreateJobResponseCollectionWithIncludedSectionDataInnerToJSON(value.data),
    };
}

