/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostCatalogItemResponseData } from './PostCatalogItemResponseData';
import {
    PostCatalogItemResponseDataFromJSON,
    PostCatalogItemResponseDataFromJSONTyped,
    PostCatalogItemResponseDataToJSON,
} from './PostCatalogItemResponseData';

/**
 * 
 * @export
 * @interface PostCatalogItemResponse
 */
export interface PostCatalogItemResponse {
    /**
     * 
     * @type {PostCatalogItemResponseData}
     * @memberof PostCatalogItemResponse
     */
    data: PostCatalogItemResponseData;
}

/**
 * Check if a given object implements the PostCatalogItemResponse interface.
 */
export function instanceOfPostCatalogItemResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostCatalogItemResponseFromJSON(json: any): PostCatalogItemResponse {
    return PostCatalogItemResponseFromJSONTyped(json, false);
}

export function PostCatalogItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCatalogItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': PostCatalogItemResponseDataFromJSON(json['data']),
    };
}

export function PostCatalogItemResponseToJSON(value?: PostCatalogItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PostCatalogItemResponseDataToJSON(value.data),
    };
}

