/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks } from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import {
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSONTyped,
    GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON,
} from './GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks';
import type { PostMetricAggregateResponseDataAttributes } from './PostMetricAggregateResponseDataAttributes';
import {
    PostMetricAggregateResponseDataAttributesFromJSON,
    PostMetricAggregateResponseDataAttributesFromJSONTyped,
    PostMetricAggregateResponseDataAttributesToJSON,
} from './PostMetricAggregateResponseDataAttributes';

/**
 * 
 * @export
 * @interface PostMetricAggregateResponseData
 */
export interface PostMetricAggregateResponseData {
    /**
     * 
     * @type {string}
     * @memberof PostMetricAggregateResponseData
     */
    type: PostMetricAggregateResponseDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PostMetricAggregateResponseData
     */
    id: string;
    /**
     * 
     * @type {PostMetricAggregateResponseDataAttributes}
     * @memberof PostMetricAggregateResponseData
     */
    attributes: PostMetricAggregateResponseDataAttributes;
    /**
     * 
     * @type {GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks}
     * @memberof PostMetricAggregateResponseData
     */
    links: GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinks;
}


/**
 * @export
 */
export const PostMetricAggregateResponseDataTypeEnum = {
    MetricAggregate: 'metric-aggregate'
} as const;
export type PostMetricAggregateResponseDataTypeEnum = typeof PostMetricAggregateResponseDataTypeEnum[keyof typeof PostMetricAggregateResponseDataTypeEnum];


/**
 * Check if a given object implements the PostMetricAggregateResponseData interface.
 */
export function instanceOfPostMetricAggregateResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function PostMetricAggregateResponseDataFromJSON(json: any): PostMetricAggregateResponseData {
    return PostMetricAggregateResponseDataFromJSONTyped(json, false);
}

export function PostMetricAggregateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMetricAggregateResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': PostMetricAggregateResponseDataAttributesFromJSON(json['attributes']),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksFromJSON(json['links']),
    };
}

export function PostMetricAggregateResponseDataToJSON(value?: PostMetricAggregateResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': PostMetricAggregateResponseDataAttributesToJSON(value.attributes),
        'links': GetCatalogItemResponseCollectionWithIncludedSectionDataInnerLinksToJSON(value.links),
    };
}

