/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetListResponseCollectionDataInner } from './GetListResponseCollectionDataInner';
import {
    GetListResponseCollectionDataInnerFromJSON,
    GetListResponseCollectionDataInnerFromJSONTyped,
    GetListResponseCollectionDataInnerToJSON,
} from './GetListResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface PostListResponse
 */
export interface PostListResponse {
    /**
     * 
     * @type {GetListResponseCollectionDataInner}
     * @memberof PostListResponse
     */
    data: GetListResponseCollectionDataInner;
}

/**
 * Check if a given object implements the PostListResponse interface.
 */
export function instanceOfPostListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostListResponseFromJSON(json: any): PostListResponse {
    return PostListResponseFromJSONTyped(json, false);
}

export function PostListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetListResponseCollectionDataInnerFromJSON(json['data']),
    };
}

export function PostListResponseToJSON(value?: PostListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetListResponseCollectionDataInnerToJSON(value.data),
    };
}

