/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogVariantDeleteJobResponseCollectionDataInner } from './GetCatalogVariantDeleteJobResponseCollectionDataInner';
import {
    GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSON,
    GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSONTyped,
    GetCatalogVariantDeleteJobResponseCollectionDataInnerToJSON,
} from './GetCatalogVariantDeleteJobResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface PostCatalogVariantDeleteJobResponse
 */
export interface PostCatalogVariantDeleteJobResponse {
    /**
     * 
     * @type {GetCatalogVariantDeleteJobResponseCollectionDataInner}
     * @memberof PostCatalogVariantDeleteJobResponse
     */
    data: GetCatalogVariantDeleteJobResponseCollectionDataInner;
}

/**
 * Check if a given object implements the PostCatalogVariantDeleteJobResponse interface.
 */
export function instanceOfPostCatalogVariantDeleteJobResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostCatalogVariantDeleteJobResponseFromJSON(json: any): PostCatalogVariantDeleteJobResponse {
    return PostCatalogVariantDeleteJobResponseFromJSONTyped(json, false);
}

export function PostCatalogVariantDeleteJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCatalogVariantDeleteJobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCatalogVariantDeleteJobResponseCollectionDataInnerFromJSON(json['data']),
    };
}

export function PostCatalogVariantDeleteJobResponseToJSON(value?: PostCatalogVariantDeleteJobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCatalogVariantDeleteJobResponseCollectionDataInnerToJSON(value.data),
    };
}

