/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCatalogCategoryDeleteJobResponseCollectionDataInner } from './GetCatalogCategoryDeleteJobResponseCollectionDataInner';
import {
    GetCatalogCategoryDeleteJobResponseCollectionDataInnerFromJSON,
    GetCatalogCategoryDeleteJobResponseCollectionDataInnerFromJSONTyped,
    GetCatalogCategoryDeleteJobResponseCollectionDataInnerToJSON,
} from './GetCatalogCategoryDeleteJobResponseCollectionDataInner';

/**
 * 
 * @export
 * @interface PostCatalogCategoryDeleteJobResponse
 */
export interface PostCatalogCategoryDeleteJobResponse {
    /**
     * 
     * @type {GetCatalogCategoryDeleteJobResponseCollectionDataInner}
     * @memberof PostCatalogCategoryDeleteJobResponse
     */
    data: GetCatalogCategoryDeleteJobResponseCollectionDataInner;
}

/**
 * Check if a given object implements the PostCatalogCategoryDeleteJobResponse interface.
 */
export function instanceOfPostCatalogCategoryDeleteJobResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function PostCatalogCategoryDeleteJobResponseFromJSON(json: any): PostCatalogCategoryDeleteJobResponse {
    return PostCatalogCategoryDeleteJobResponseFromJSONTyped(json, false);
}

export function PostCatalogCategoryDeleteJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCatalogCategoryDeleteJobResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCatalogCategoryDeleteJobResponseCollectionDataInnerFromJSON(json['data']),
    };
}

export function PostCatalogCategoryDeleteJobResponseToJSON(value?: PostCatalogCategoryDeleteJobResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCatalogCategoryDeleteJobResponseCollectionDataInnerToJSON(value.data),
    };
}

