/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProfileCreateQueryAsSubResource } from './ProfileCreateQueryAsSubResource';
import {
    ProfileCreateQueryAsSubResourceFromJSON,
    ProfileCreateQueryAsSubResourceFromJSONTyped,
    ProfileCreateQueryAsSubResourceToJSON,
} from './ProfileCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface ProfileCreateQuery
 */
export interface ProfileCreateQuery {
    /**
     * 
     * @type {ProfileCreateQueryAsSubResource}
     * @memberof ProfileCreateQuery
     */
    data: ProfileCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the ProfileCreateQuery interface.
 */
export function instanceOfProfileCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function ProfileCreateQueryFromJSON(json: any): ProfileCreateQuery {
    return ProfileCreateQueryFromJSONTyped(json, false);
}

export function ProfileCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ProfileCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function ProfileCreateQueryToJSON(value?: ProfileCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ProfileCreateQueryAsSubResourceToJSON(value.data),
    };
}

