/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ProfileLocationLatitude
 * 
 * @export
 */
export type ProfileLocationLatitude = number | string;

export function ProfileLocationLatitudeFromJSON(json: any): ProfileLocationLatitude {
    return ProfileLocationLatitudeFromJSONTyped(json, false);
}

export function ProfileLocationLatitudeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileLocationLatitude {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...numberFromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function ProfileLocationLatitudeToJSON(value?: ProfileLocationLatitude | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

