/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    StaticScheduleOptions,
    instanceOfStaticScheduleOptions,
    StaticScheduleOptionsFromJSON,
    StaticScheduleOptionsFromJSONTyped,
    StaticScheduleOptionsToJSON,
} from './StaticScheduleOptions';
import {
    ThrottledScheduleOptions,
    instanceOfThrottledScheduleOptions,
    ThrottledScheduleOptionsFromJSON,
    ThrottledScheduleOptionsFromJSONTyped,
    ThrottledScheduleOptionsToJSON,
} from './ThrottledScheduleOptions';

/**
 * @type SendStrategySubObjectOptions
 * 
 * @export
 */
export type SendStrategySubObjectOptions = StaticScheduleOptions | ThrottledScheduleOptions;

export function SendStrategySubObjectOptionsFromJSON(json: any): SendStrategySubObjectOptions {
    return SendStrategySubObjectOptionsFromJSONTyped(json, false);
}

export function SendStrategySubObjectOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendStrategySubObjectOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...StaticScheduleOptionsFromJSONTyped(json, true), ...ThrottledScheduleOptionsFromJSONTyped(json, true) };
}

export function SendStrategySubObjectOptionsToJSON(value?: SendStrategySubObjectOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfStaticScheduleOptions(value)) {
        return StaticScheduleOptionsToJSON(value as StaticScheduleOptions);
    }
    if (instanceOfThrottledScheduleOptions(value)) {
        return ThrottledScheduleOptionsToJSON(value as ThrottledScheduleOptions);
    }

    return {};
}

