/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendOptions
 */
export interface SendOptions {
    /**
     * 
     * @type {boolean}
     * @memberof SendOptions
     */
    useSmartSending: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SendOptions
     */
    isTransactional: boolean;
}

/**
 * Check if a given object implements the SendOptions interface.
 */
export function instanceOfSendOptions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "useSmartSending" in value;
    isInstance = isInstance && "isTransactional" in value;

    return isInstance;
}

export function SendOptionsFromJSON(json: any): SendOptions {
    return SendOptionsFromJSONTyped(json, false);
}

export function SendOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'useSmartSending': json['use_smart_sending'],
        'isTransactional': json['is_transactional'],
    };
}

export function SendOptionsToJSON(value?: SendOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'use_smart_sending': value.useSmartSending,
        'is_transactional': value.isTransactional,
    };
}

