/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SMSMessageContent
 */
export interface SMSMessageContent {
    /**
     * 
     * @type {string}
     * @memberof SMSMessageContent
     */
    body: string;
    /**
     * 
     * @type {string}
     * @memberof SMSMessageContent
     */
    media: string;
}

/**
 * Check if a given object implements the SMSMessageContent interface.
 */
export function instanceOfSMSMessageContent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;
    isInstance = isInstance && "media" in value;

    return isInstance;
}

export function SMSMessageContentFromJSON(json: any): SMSMessageContent {
    return SMSMessageContentFromJSONTyped(json, false);
}

export function SMSMessageContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SMSMessageContent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
        'media': json['media'],
    };
}

export function SMSMessageContentToJSON(value?: SMSMessageContent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'media': value.media,
    };
}

