/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubscriptionCreateJobCreateQueryAsSubResourceAttributes } from './SubscriptionCreateJobCreateQueryAsSubResourceAttributes';
import {
    SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSON,
    SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    SubscriptionCreateJobCreateQueryAsSubResourceAttributesToJSON,
} from './SubscriptionCreateJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface SubscriptionCreateJobCreateQueryAsSubResource
 */
export interface SubscriptionCreateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResource
     */
    type: SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {SubscriptionCreateJobCreateQueryAsSubResourceAttributes}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResource
     */
    attributes: SubscriptionCreateJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = {
    ProfileSubscriptionBulkCreateJob: 'profile-subscription-bulk-create-job'
} as const;
export type SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = typeof SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum[keyof typeof SubscriptionCreateJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the SubscriptionCreateJobCreateQueryAsSubResource interface.
 */
export function instanceOfSubscriptionCreateJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function SubscriptionCreateJobCreateQueryAsSubResourceFromJSON(json: any): SubscriptionCreateJobCreateQueryAsSubResource {
    return SubscriptionCreateJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function SubscriptionCreateJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function SubscriptionCreateJobCreateQueryAsSubResourceToJSON(value?: SubscriptionCreateJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': SubscriptionCreateJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

