/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './Subscription';

/**
 * 
 * @export
 * @interface SubscriptionCreateJobCreateQueryAsSubResourceAttributes
 */
export interface SubscriptionCreateJobCreateQueryAsSubResourceAttributes {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResourceAttributes
     */
    listId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResourceAttributes
     */
    customSource?: string;
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof SubscriptionCreateJobCreateQueryAsSubResourceAttributes
     */
    subscriptions: Array<Subscription>;
}

/**
 * Check if a given object implements the SubscriptionCreateJobCreateQueryAsSubResourceAttributes interface.
 */
export function instanceOfSubscriptionCreateJobCreateQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "listId" in value;
    isInstance = isInstance && "subscriptions" in value;

    return isInstance;
}

export function SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSON(json: any): SubscriptionCreateJobCreateQueryAsSubResourceAttributes {
    return SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function SubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateJobCreateQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listId': json['list_id'],
        'customSource': !exists(json, 'custom_source') ? undefined : json['custom_source'],
        'subscriptions': ((json['subscriptions'] as Array<any>).map(SubscriptionFromJSON)),
    };
}

export function SubscriptionCreateJobCreateQueryAsSubResourceAttributesToJSON(value?: SubscriptionCreateJobCreateQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'list_id': value.listId,
        'custom_source': value.customSource,
        'subscriptions': ((value.subscriptions as Array<any>).map(SubscriptionToJSON)),
    };
}

