/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListCreateQueryAsSubResourceAttributes } from './ListCreateQueryAsSubResourceAttributes';
import {
    ListCreateQueryAsSubResourceAttributesFromJSON,
    ListCreateQueryAsSubResourceAttributesFromJSONTyped,
    ListCreateQueryAsSubResourceAttributesToJSON,
} from './ListCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface TagUpdateQueryAsSubResource
 */
export interface TagUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof TagUpdateQueryAsSubResource
     */
    type: TagUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TagUpdateQueryAsSubResource
     */
    id: string;
    /**
     * 
     * @type {ListCreateQueryAsSubResourceAttributes}
     * @memberof TagUpdateQueryAsSubResource
     */
    attributes: ListCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const TagUpdateQueryAsSubResourceTypeEnum = {
    Tag: 'tag'
} as const;
export type TagUpdateQueryAsSubResourceTypeEnum = typeof TagUpdateQueryAsSubResourceTypeEnum[keyof typeof TagUpdateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the TagUpdateQueryAsSubResource interface.
 */
export function instanceOfTagUpdateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function TagUpdateQueryAsSubResourceFromJSON(json: any): TagUpdateQueryAsSubResource {
    return TagUpdateQueryAsSubResourceFromJSONTyped(json, false);
}

export function TagUpdateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagUpdateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': ListCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function TagUpdateQueryAsSubResourceToJSON(value?: TagUpdateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': ListCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

