/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateCloneQueryAsSubResourceAttributes } from './TemplateCloneQueryAsSubResourceAttributes';
import {
    TemplateCloneQueryAsSubResourceAttributesFromJSON,
    TemplateCloneQueryAsSubResourceAttributesFromJSONTyped,
    TemplateCloneQueryAsSubResourceAttributesToJSON,
} from './TemplateCloneQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface TemplateCloneQueryAsSubResource
 */
export interface TemplateCloneQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof TemplateCloneQueryAsSubResource
     */
    type: TemplateCloneQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {TemplateCloneQueryAsSubResourceAttributes}
     * @memberof TemplateCloneQueryAsSubResource
     */
    attributes: TemplateCloneQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const TemplateCloneQueryAsSubResourceTypeEnum = {
    Template: 'template'
} as const;
export type TemplateCloneQueryAsSubResourceTypeEnum = typeof TemplateCloneQueryAsSubResourceTypeEnum[keyof typeof TemplateCloneQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the TemplateCloneQueryAsSubResource interface.
 */
export function instanceOfTemplateCloneQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function TemplateCloneQueryAsSubResourceFromJSON(json: any): TemplateCloneQueryAsSubResource {
    return TemplateCloneQueryAsSubResourceFromJSONTyped(json, false);
}

export function TemplateCloneQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCloneQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': TemplateCloneQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function TemplateCloneQueryAsSubResourceToJSON(value?: TemplateCloneQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': TemplateCloneQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

