/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateCreateQueryAsSubResourceAttributes } from './TemplateCreateQueryAsSubResourceAttributes';
import {
    TemplateCreateQueryAsSubResourceAttributesFromJSON,
    TemplateCreateQueryAsSubResourceAttributesFromJSONTyped,
    TemplateCreateQueryAsSubResourceAttributesToJSON,
} from './TemplateCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface TemplateCreateQueryAsSubResource
 */
export interface TemplateCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateQueryAsSubResource
     */
    type: TemplateCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {TemplateCreateQueryAsSubResourceAttributes}
     * @memberof TemplateCreateQueryAsSubResource
     */
    attributes: TemplateCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const TemplateCreateQueryAsSubResourceTypeEnum = {
    Template: 'template'
} as const;
export type TemplateCreateQueryAsSubResourceTypeEnum = typeof TemplateCreateQueryAsSubResourceTypeEnum[keyof typeof TemplateCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the TemplateCreateQueryAsSubResource interface.
 */
export function instanceOfTemplateCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function TemplateCreateQueryAsSubResourceFromJSON(json: any): TemplateCreateQueryAsSubResource {
    return TemplateCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function TemplateCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': TemplateCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function TemplateCreateQueryAsSubResourceToJSON(value?: TemplateCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': TemplateCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

