/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateUpdateQueryAsSubResourceAttributes } from './TemplateUpdateQueryAsSubResourceAttributes';
import {
    TemplateUpdateQueryAsSubResourceAttributesFromJSON,
    TemplateUpdateQueryAsSubResourceAttributesFromJSONTyped,
    TemplateUpdateQueryAsSubResourceAttributesToJSON,
} from './TemplateUpdateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface TemplateUpdateQueryAsSubResource
 */
export interface TemplateUpdateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateQueryAsSubResource
     */
    type: TemplateUpdateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TemplateUpdateQueryAsSubResource
     */
    id: string;
    /**
     * 
     * @type {TemplateUpdateQueryAsSubResourceAttributes}
     * @memberof TemplateUpdateQueryAsSubResource
     */
    attributes: TemplateUpdateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const TemplateUpdateQueryAsSubResourceTypeEnum = {
    Template: 'template'
} as const;
export type TemplateUpdateQueryAsSubResourceTypeEnum = typeof TemplateUpdateQueryAsSubResourceTypeEnum[keyof typeof TemplateUpdateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the TemplateUpdateQueryAsSubResource interface.
 */
export function instanceOfTemplateUpdateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function TemplateUpdateQueryAsSubResourceFromJSON(json: any): TemplateUpdateQueryAsSubResource {
    return TemplateUpdateQueryAsSubResourceFromJSONTyped(json, false);
}

export function TemplateUpdateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateUpdateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': TemplateUpdateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function TemplateUpdateQueryAsSubResourceToJSON(value?: TemplateUpdateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': TemplateUpdateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

