/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateCreateQueryAsSubResource } from './TemplateCreateQueryAsSubResource';
import {
    TemplateCreateQueryAsSubResourceFromJSON,
    TemplateCreateQueryAsSubResourceFromJSONTyped,
    TemplateCreateQueryAsSubResourceToJSON,
} from './TemplateCreateQueryAsSubResource';

/**
 * 
 * @export
 * @interface TemplateCreateQuery
 */
export interface TemplateCreateQuery {
    /**
     * 
     * @type {TemplateCreateQueryAsSubResource}
     * @memberof TemplateCreateQuery
     */
    data: TemplateCreateQueryAsSubResource;
}

/**
 * Check if a given object implements the TemplateCreateQuery interface.
 */
export function instanceOfTemplateCreateQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function TemplateCreateQueryFromJSON(json: any): TemplateCreateQuery {
    return TemplateCreateQueryFromJSONTyped(json, false);
}

export function TemplateCreateQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCreateQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': TemplateCreateQueryAsSubResourceFromJSON(json['data']),
    };
}

export function TemplateCreateQueryToJSON(value?: TemplateCreateQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TemplateCreateQueryAsSubResourceToJSON(value.data),
    };
}

