/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes } from './UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes';
import {
    UnsubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSON,
    UnsubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    UnsubscriptionCreateJobCreateQueryAsSubResourceAttributesToJSON,
} from './UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface UnsubscriptionCreateJobCreateQueryAsSubResource
 */
export interface UnsubscriptionCreateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof UnsubscriptionCreateJobCreateQueryAsSubResource
     */
    type: UnsubscriptionCreateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes}
     * @memberof UnsubscriptionCreateJobCreateQueryAsSubResource
     */
    attributes: UnsubscriptionCreateJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const UnsubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = {
    ProfileUnsubscriptionBulkCreateJob: 'profile-unsubscription-bulk-create-job'
} as const;
export type UnsubscriptionCreateJobCreateQueryAsSubResourceTypeEnum = typeof UnsubscriptionCreateJobCreateQueryAsSubResourceTypeEnum[keyof typeof UnsubscriptionCreateJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the UnsubscriptionCreateJobCreateQueryAsSubResource interface.
 */
export function instanceOfUnsubscriptionCreateJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function UnsubscriptionCreateJobCreateQueryAsSubResourceFromJSON(json: any): UnsubscriptionCreateJobCreateQueryAsSubResource {
    return UnsubscriptionCreateJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function UnsubscriptionCreateJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscriptionCreateJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': UnsubscriptionCreateJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function UnsubscriptionCreateJobCreateQueryAsSubResourceToJSON(value?: UnsubscriptionCreateJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': UnsubscriptionCreateJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

