/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SuppressionCreateJobCreateQueryAsSubResourceAttributes } from './SuppressionCreateJobCreateQueryAsSubResourceAttributes';
import {
    SuppressionCreateJobCreateQueryAsSubResourceAttributesFromJSON,
    SuppressionCreateJobCreateQueryAsSubResourceAttributesFromJSONTyped,
    SuppressionCreateJobCreateQueryAsSubResourceAttributesToJSON,
} from './SuppressionCreateJobCreateQueryAsSubResourceAttributes';

/**
 * 
 * @export
 * @interface UnsuppressionCreateJobCreateQueryAsSubResource
 */
export interface UnsuppressionCreateJobCreateQueryAsSubResource {
    /**
     * 
     * @type {string}
     * @memberof UnsuppressionCreateJobCreateQueryAsSubResource
     */
    type: UnsuppressionCreateJobCreateQueryAsSubResourceTypeEnum;
    /**
     * 
     * @type {SuppressionCreateJobCreateQueryAsSubResourceAttributes}
     * @memberof UnsuppressionCreateJobCreateQueryAsSubResource
     */
    attributes: SuppressionCreateJobCreateQueryAsSubResourceAttributes;
}


/**
 * @export
 */
export const UnsuppressionCreateJobCreateQueryAsSubResourceTypeEnum = {
    ProfileUnsuppressionBulkCreateJob: 'profile-unsuppression-bulk-create-job'
} as const;
export type UnsuppressionCreateJobCreateQueryAsSubResourceTypeEnum = typeof UnsuppressionCreateJobCreateQueryAsSubResourceTypeEnum[keyof typeof UnsuppressionCreateJobCreateQueryAsSubResourceTypeEnum];


/**
 * Check if a given object implements the UnsuppressionCreateJobCreateQueryAsSubResource interface.
 */
export function instanceOfUnsuppressionCreateJobCreateQueryAsSubResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function UnsuppressionCreateJobCreateQueryAsSubResourceFromJSON(json: any): UnsuppressionCreateJobCreateQueryAsSubResource {
    return UnsuppressionCreateJobCreateQueryAsSubResourceFromJSONTyped(json, false);
}

export function UnsuppressionCreateJobCreateQueryAsSubResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsuppressionCreateJobCreateQueryAsSubResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': SuppressionCreateJobCreateQueryAsSubResourceAttributesFromJSON(json['attributes']),
    };
}

export function UnsuppressionCreateJobCreateQueryAsSubResourceToJSON(value?: UnsuppressionCreateJobCreateQueryAsSubResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': SuppressionCreateJobCreateQueryAsSubResourceAttributesToJSON(value.attributes),
    };
}

