/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V2TemplateRenderQueryAsSubResource } from './V2TemplateRenderQueryAsSubResource';
import {
    V2TemplateRenderQueryAsSubResourceFromJSON,
    V2TemplateRenderQueryAsSubResourceFromJSONTyped,
    V2TemplateRenderQueryAsSubResourceToJSON,
} from './V2TemplateRenderQueryAsSubResource';

/**
 * 
 * @export
 * @interface V2TemplateRenderQuery
 */
export interface V2TemplateRenderQuery {
    /**
     * 
     * @type {V2TemplateRenderQueryAsSubResource}
     * @memberof V2TemplateRenderQuery
     */
    data: V2TemplateRenderQueryAsSubResource;
}

/**
 * Check if a given object implements the V2TemplateRenderQuery interface.
 */
export function instanceOfV2TemplateRenderQuery(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function V2TemplateRenderQueryFromJSON(json: any): V2TemplateRenderQuery {
    return V2TemplateRenderQueryFromJSONTyped(json, false);
}

export function V2TemplateRenderQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2TemplateRenderQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': V2TemplateRenderQueryAsSubResourceFromJSON(json['data']),
    };
}

export function V2TemplateRenderQueryToJSON(value?: V2TemplateRenderQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': V2TemplateRenderQueryAsSubResourceToJSON(value.data),
    };
}

