/* tslint:disable */
/* eslint-disable */
/**
 * Klaviyo API
 * The Klaviyo REST API. Please visit https://developers.klaviyo.com for more details.
 *
 * The version of the OpenAPI document: 2022-10-17
 * Contact: developers@klaviyo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2TemplateRenderQueryAsSubResourceAttributes
 */
export interface V2TemplateRenderQueryAsSubResourceAttributes {
    /**
     * 
     * @type {object}
     * @memberof V2TemplateRenderQueryAsSubResourceAttributes
     */
    context: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof V2TemplateRenderQueryAsSubResourceAttributes
     */
    returnFields?: Array<string>;
}

/**
 * Check if a given object implements the V2TemplateRenderQueryAsSubResourceAttributes interface.
 */
export function instanceOfV2TemplateRenderQueryAsSubResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "context" in value;

    return isInstance;
}

export function V2TemplateRenderQueryAsSubResourceAttributesFromJSON(json: any): V2TemplateRenderQueryAsSubResourceAttributes {
    return V2TemplateRenderQueryAsSubResourceAttributesFromJSONTyped(json, false);
}

export function V2TemplateRenderQueryAsSubResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2TemplateRenderQueryAsSubResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'context': json['context'],
        'returnFields': !exists(json, 'return_fields') ? undefined : json['return_fields'],
    };
}

export function V2TemplateRenderQueryAsSubResourceAttributesToJSON(value?: V2TemplateRenderQueryAsSubResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'context': value.context,
        'return_fields': value.returnFields,
    };
}

